// Code generated by protoc-gen-go. DO NOT EDIT.
// source: cinema.proto

package cinema

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateHallRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,2,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,3,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHallRequest) Reset()         { *m = CreateHallRequest{} }
func (m *CreateHallRequest) String() string { return proto.CompactTextString(m) }
func (*CreateHallRequest) ProtoMessage()    {}
func (*CreateHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{0}
}

func (m *CreateHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHallRequest.Unmarshal(m, b)
}
func (m *CreateHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHallRequest.Marshal(b, m, deterministic)
}
func (m *CreateHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHallRequest.Merge(m, src)
}
func (m *CreateHallRequest) XXX_Size() int {
	return xxx_messageInfo_CreateHallRequest.Size(m)
}
func (m *CreateHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHallRequest proto.InternalMessageInfo

func (m *CreateHallRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateHallRequest) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CreateHallRequest) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

type CreateHallResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateHallResult) Reset()         { *m = CreateHallResult{} }
func (m *CreateHallResult) String() string { return proto.CompactTextString(m) }
func (*CreateHallResult) ProtoMessage()    {}
func (*CreateHallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{1}
}

func (m *CreateHallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateHallResult.Unmarshal(m, b)
}
func (m *CreateHallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateHallResult.Marshal(b, m, deterministic)
}
func (m *CreateHallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateHallResult.Merge(m, src)
}
func (m *CreateHallResult) XXX_Size() int {
	return xxx_messageInfo_CreateHallResult.Size(m)
}
func (m *CreateHallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateHallResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateHallResult proto.InternalMessageInfo

func (m *CreateHallResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteHallRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHallRequest) Reset()         { *m = DeleteHallRequest{} }
func (m *DeleteHallRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteHallRequest) ProtoMessage()    {}
func (*DeleteHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{2}
}

func (m *DeleteHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHallRequest.Unmarshal(m, b)
}
func (m *DeleteHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHallRequest.Marshal(b, m, deterministic)
}
func (m *DeleteHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHallRequest.Merge(m, src)
}
func (m *DeleteHallRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteHallRequest.Size(m)
}
func (m *DeleteHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHallRequest proto.InternalMessageInfo

func (m *DeleteHallRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteHallResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteHallResult) Reset()         { *m = DeleteHallResult{} }
func (m *DeleteHallResult) String() string { return proto.CompactTextString(m) }
func (*DeleteHallResult) ProtoMessage()    {}
func (*DeleteHallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{3}
}

func (m *DeleteHallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteHallResult.Unmarshal(m, b)
}
func (m *DeleteHallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteHallResult.Marshal(b, m, deterministic)
}
func (m *DeleteHallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteHallResult.Merge(m, src)
}
func (m *DeleteHallResult) XXX_Size() int {
	return xxx_messageInfo_DeleteHallResult.Size(m)
}
func (m *DeleteHallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteHallResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteHallResult proto.InternalMessageInfo

func (m *DeleteHallResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type GetHallListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetHallListRequest) Reset()         { *m = GetHallListRequest{} }
func (m *GetHallListRequest) String() string { return proto.CompactTextString(m) }
func (*GetHallListRequest) ProtoMessage()    {}
func (*GetHallListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{4}
}

func (m *GetHallListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHallListRequest.Unmarshal(m, b)
}
func (m *GetHallListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHallListRequest.Marshal(b, m, deterministic)
}
func (m *GetHallListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHallListRequest.Merge(m, src)
}
func (m *GetHallListRequest) XXX_Size() int {
	return xxx_messageInfo_GetHallListRequest.Size(m)
}
func (m *GetHallListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHallListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetHallListRequest proto.InternalMessageInfo

type FreeSeatsRequest struct {
	HallID               int32    `protobuf:"varint,1,opt,name=HallID,json=hallID,proto3" json:"HallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSeatsRequest) Reset()         { *m = FreeSeatsRequest{} }
func (m *FreeSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsRequest) ProtoMessage()    {}
func (*FreeSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{5}
}

func (m *FreeSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsRequest.Unmarshal(m, b)
}
func (m *FreeSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsRequest.Marshal(b, m, deterministic)
}
func (m *FreeSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsRequest.Merge(m, src)
}
func (m *FreeSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsRequest.Size(m)
}
func (m *FreeSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsRequest proto.InternalMessageInfo

func (m *FreeSeatsRequest) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type FreeSeatsResult struct {
	FreeSeats            int32    `protobuf:"varint,1,opt,name=freeSeats,proto3" json:"freeSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSeatsResult) Reset()         { *m = FreeSeatsResult{} }
func (m *FreeSeatsResult) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsResult) ProtoMessage()    {}
func (*FreeSeatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{6}
}

func (m *FreeSeatsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsResult.Unmarshal(m, b)
}
func (m *FreeSeatsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsResult.Marshal(b, m, deterministic)
}
func (m *FreeSeatsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsResult.Merge(m, src)
}
func (m *FreeSeatsResult) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsResult.Size(m)
}
func (m *FreeSeatsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsResult.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsResult proto.InternalMessageInfo

func (m *FreeSeatsResult) GetFreeSeats() int32 {
	if m != nil {
		return m.FreeSeats
	}
	return 0
}

type GetHallListResult struct {
	CHall                []*CinemaHall `protobuf:"bytes,1,rep,name=cHall,proto3" json:"cHall,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *GetHallListResult) Reset()         { *m = GetHallListResult{} }
func (m *GetHallListResult) String() string { return proto.CompactTextString(m) }
func (*GetHallListResult) ProtoMessage()    {}
func (*GetHallListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{7}
}

func (m *GetHallListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetHallListResult.Unmarshal(m, b)
}
func (m *GetHallListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetHallListResult.Marshal(b, m, deterministic)
}
func (m *GetHallListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetHallListResult.Merge(m, src)
}
func (m *GetHallListResult) XXX_Size() int {
	return xxx_messageInfo_GetHallListResult.Size(m)
}
func (m *GetHallListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetHallListResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetHallListResult proto.InternalMessageInfo

func (m *GetHallListResult) GetCHall() []*CinemaHall {
	if m != nil {
		return m.CHall
	}
	return nil
}

type CinemaHall struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rows                 int32    `protobuf:"varint,3,opt,name=rows,proto3" json:"rows,omitempty"`
	Cols                 int32    `protobuf:"varint,4,opt,name=cols,proto3" json:"cols,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CinemaHall) Reset()         { *m = CinemaHall{} }
func (m *CinemaHall) String() string { return proto.CompactTextString(m) }
func (*CinemaHall) ProtoMessage()    {}
func (*CinemaHall) Descriptor() ([]byte, []int) {
	return fileDescriptor_12b50437886e4171, []int{8}
}

func (m *CinemaHall) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CinemaHall.Unmarshal(m, b)
}
func (m *CinemaHall) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CinemaHall.Marshal(b, m, deterministic)
}
func (m *CinemaHall) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CinemaHall.Merge(m, src)
}
func (m *CinemaHall) XXX_Size() int {
	return xxx_messageInfo_CinemaHall.Size(m)
}
func (m *CinemaHall) XXX_DiscardUnknown() {
	xxx_messageInfo_CinemaHall.DiscardUnknown(m)
}

var xxx_messageInfo_CinemaHall proto.InternalMessageInfo

func (m *CinemaHall) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *CinemaHall) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CinemaHall) GetRows() int32 {
	if m != nil {
		return m.Rows
	}
	return 0
}

func (m *CinemaHall) GetCols() int32 {
	if m != nil {
		return m.Cols
	}
	return 0
}

func init() {
	proto.RegisterType((*CreateHallRequest)(nil), "cinema.CreateHallRequest")
	proto.RegisterType((*CreateHallResult)(nil), "cinema.CreateHallResult")
	proto.RegisterType((*DeleteHallRequest)(nil), "cinema.DeleteHallRequest")
	proto.RegisterType((*DeleteHallResult)(nil), "cinema.DeleteHallResult")
	proto.RegisterType((*GetHallListRequest)(nil), "cinema.GetHallListRequest")
	proto.RegisterType((*FreeSeatsRequest)(nil), "cinema.FreeSeatsRequest")
	proto.RegisterType((*FreeSeatsResult)(nil), "cinema.FreeSeatsResult")
	proto.RegisterType((*GetHallListResult)(nil), "cinema.GetHallListResult")
	proto.RegisterType((*CinemaHall)(nil), "cinema.CinemaHall")
}

func init() { proto.RegisterFile("cinema.proto", fileDescriptor_12b50437886e4171) }

var fileDescriptor_12b50437886e4171 = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x93, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0xd7, 0x6e, 0x2b, 0xdb, 0x9d, 0xe8, 0x16, 0x44, 0xbb, 0x22, 0x32, 0xe2, 0x4b, 0xf1,
	0x61, 0xc2, 0x7c, 0x16, 0x91, 0x8d, 0xa9, 0x20, 0x08, 0xf5, 0xc5, 0xd7, 0xda, 0xdd, 0x61, 0x31,
	0x5b, 0xb5, 0x49, 0xf1, 0xc7, 0xf8, 0x67, 0x25, 0xb7, 0x5d, 0xd3, 0x75, 0x7d, 0x5a, 0x72, 0x72,
	0x72, 0xce, 0x72, 0x3f, 0x0a, 0x47, 0x51, 0xbc, 0xc5, 0x4d, 0x38, 0xfd, 0x4e, 0x13, 0x95, 0x30,
	0x27, 0xdf, 0xf1, 0x57, 0x18, 0xcd, 0x53, 0x0c, 0x15, 0x3e, 0x85, 0x42, 0x04, 0xf8, 0x93, 0xa1,
	0x54, 0x8c, 0x41, 0x67, 0x1b, 0x6e, 0xd0, 0xb5, 0x26, 0x96, 0xdf, 0x0f, 0x68, 0xad, 0xb5, 0x34,
	0xf9, 0x95, 0xae, 0x3d, 0xb1, 0xfc, 0x6e, 0x40, 0x6b, 0xad, 0x45, 0x89, 0x90, 0x6e, 0x3b, 0xd7,
	0xf4, 0x9a, 0x73, 0x18, 0x56, 0x03, 0x65, 0x26, 0x14, 0x3b, 0x06, 0x3b, 0x5e, 0x51, 0x5a, 0x37,
	0xb0, 0xe3, 0x15, 0xbf, 0x82, 0xd1, 0x02, 0x05, 0xee, 0x97, 0xd6, 0x4d, 0x33, 0x18, 0x56, 0x4d,
	0x14, 0x74, 0x09, 0x20, 0xb3, 0x28, 0x42, 0x29, 0xd7, 0x99, 0x20, 0x6f, 0x2f, 0xa8, 0x28, 0xfc,
	0x14, 0xd8, 0x23, 0x2a, 0x7d, 0xe1, 0x25, 0x96, 0xaa, 0x48, 0xe6, 0xd7, 0x30, 0x5c, 0xa6, 0x88,
	0x6f, 0x18, 0x2a, 0xb9, 0x6b, 0x3b, 0x03, 0x47, 0xdb, 0x9e, 0x17, 0x45, 0xa3, 0xf3, 0x49, 0x3b,
	0x7e, 0x03, 0x27, 0x15, 0x2f, 0x95, 0x5e, 0x40, 0x7f, 0xbd, 0x93, 0x0a, 0xb7, 0x11, 0xf8, 0x1d,
	0x8c, 0xf6, 0x2a, 0xe9, 0x8a, 0x0f, 0xdd, 0x48, 0x4b, 0xae, 0x35, 0x69, 0xfb, 0x83, 0x19, 0x9b,
	0x16, 0xb3, 0x9f, 0xd3, 0x0f, 0x3d, 0x28, 0x37, 0xf0, 0x77, 0x00, 0x23, 0xd6, 0x67, 0x50, 0x82,
	0xb0, 0x1b, 0x40, 0xb4, 0x1b, 0x40, 0x74, 0x0c, 0x88, 0xd9, 0x9f, 0x0d, 0x4e, 0x1e, 0xcd, 0xe6,
	0x00, 0x86, 0x09, 0x1b, 0x97, 0xff, 0xa6, 0x0e, 0xde, 0x73, 0x9b, 0x8e, 0xf4, 0x8b, 0x78, 0x4b,
	0x87, 0x18, 0x1e, 0x26, 0xe4, 0x00, 0xa4, 0x09, 0xa9, 0xe3, 0xe3, 0x2d, 0xb6, 0x84, 0x41, 0x65,
	0x5a, 0xcc, 0xdb, 0x59, 0x0f, 0xa9, 0x79, 0xe3, 0xc6, 0xb3, 0x22, 0xe7, 0x1e, 0x7a, 0x0f, 0xf2,
	0x8b, 0x08, 0xb0, 0xb2, 0xaf, 0x0e, 0xd9, 0x3b, 0x6f, 0x38, 0xc9, 0x03, 0x3e, 0x1c, 0xfa, 0x0c,
	0x6e, 0xff, 0x03, 0x00, 0x00, 0xff, 0xff, 0x24, 0x89, 0xff, 0xf8, 0x16, 0x03, 0x00, 0x00,
}
