// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package movie

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteMovieRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteMovieResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResult) Reset()         { *m = DeleteMovieResult{} }
func (m *DeleteMovieResult) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResult) ProtoMessage()    {}
func (*DeleteMovieResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *DeleteMovieResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResult.Unmarshal(m, b)
}
func (m *DeleteMovieResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResult.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResult.Merge(m, src)
}
func (m *DeleteMovieResult) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResult.Size(m)
}
func (m *DeleteMovieResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResult proto.InternalMessageInfo

func (m *DeleteMovieResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateMovieRequest struct {
	Titel                string   `protobuf:"bytes,1,opt,name=titel,proto3" json:"titel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetTitel() string {
	if m != nil {
		return m.Titel
	}
	return ""
}

type CreateMovieResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResult) Reset()         { *m = CreateMovieResult{} }
func (m *CreateMovieResult) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResult) ProtoMessage()    {}
func (*CreateMovieResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{3}
}

func (m *CreateMovieResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResult.Unmarshal(m, b)
}
func (m *CreateMovieResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResult.Marshal(b, m, deterministic)
}
func (m *CreateMovieResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResult.Merge(m, src)
}
func (m *CreateMovieResult) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResult.Size(m)
}
func (m *CreateMovieResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResult proto.InternalMessageInfo

func (m *CreateMovieResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type GetMovieListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetMovieListRequest) Reset()         { *m = GetMovieListRequest{} }
func (m *GetMovieListRequest) String() string { return proto.CompactTextString(m) }
func (*GetMovieListRequest) ProtoMessage()    {}
func (*GetMovieListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{4}
}

func (m *GetMovieListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieListRequest.Unmarshal(m, b)
}
func (m *GetMovieListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieListRequest.Marshal(b, m, deterministic)
}
func (m *GetMovieListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieListRequest.Merge(m, src)
}
func (m *GetMovieListRequest) XXX_Size() int {
	return xxx_messageInfo_GetMovieListRequest.Size(m)
}
func (m *GetMovieListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieListRequest proto.InternalMessageInfo

type GetMovieListResult struct {
	Movies               []*MovieData `protobuf:"bytes,1,rep,name=movies,proto3" json:"movies,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetMovieListResult) Reset()         { *m = GetMovieListResult{} }
func (m *GetMovieListResult) String() string { return proto.CompactTextString(m) }
func (*GetMovieListResult) ProtoMessage()    {}
func (*GetMovieListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{5}
}

func (m *GetMovieListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetMovieListResult.Unmarshal(m, b)
}
func (m *GetMovieListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetMovieListResult.Marshal(b, m, deterministic)
}
func (m *GetMovieListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetMovieListResult.Merge(m, src)
}
func (m *GetMovieListResult) XXX_Size() int {
	return xxx_messageInfo_GetMovieListResult.Size(m)
}
func (m *GetMovieListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetMovieListResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetMovieListResult proto.InternalMessageInfo

func (m *GetMovieListResult) GetMovies() []*MovieData {
	if m != nil {
		return m.Movies
	}
	return nil
}

type ExistRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistRequest) Reset()         { *m = ExistRequest{} }
func (m *ExistRequest) String() string { return proto.CompactTextString(m) }
func (*ExistRequest) ProtoMessage()    {}
func (*ExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{6}
}

func (m *ExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRequest.Unmarshal(m, b)
}
func (m *ExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRequest.Marshal(b, m, deterministic)
}
func (m *ExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRequest.Merge(m, src)
}
func (m *ExistRequest) XXX_Size() int {
	return xxx_messageInfo_ExistRequest.Size(m)
}
func (m *ExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRequest proto.InternalMessageInfo

func (m *ExistRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ExistResult struct {
	Exist                bool     `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistResult) Reset()         { *m = ExistResult{} }
func (m *ExistResult) String() string { return proto.CompactTextString(m) }
func (*ExistResult) ProtoMessage()    {}
func (*ExistResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{7}
}

func (m *ExistResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistResult.Unmarshal(m, b)
}
func (m *ExistResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistResult.Marshal(b, m, deterministic)
}
func (m *ExistResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistResult.Merge(m, src)
}
func (m *ExistResult) XXX_Size() int {
	return xxx_messageInfo_ExistResult.Size(m)
}
func (m *ExistResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExistResult proto.InternalMessageInfo

func (m *ExistResult) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type MovieData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titel                string   `protobuf:"bytes,2,opt,name=titel,proto3" json:"titel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{8}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MovieData) GetTitel() string {
	if m != nil {
		return m.Titel
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteMovieRequest)(nil), "movie.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResult)(nil), "movie.DeleteMovieResult")
	proto.RegisterType((*CreateMovieRequest)(nil), "movie.CreateMovieRequest")
	proto.RegisterType((*CreateMovieResult)(nil), "movie.CreateMovieResult")
	proto.RegisterType((*GetMovieListRequest)(nil), "movie.GetMovieListRequest")
	proto.RegisterType((*GetMovieListResult)(nil), "movie.GetMovieListResult")
	proto.RegisterType((*ExistRequest)(nil), "movie.ExistRequest")
	proto.RegisterType((*ExistResult)(nil), "movie.ExistResult")
	proto.RegisterType((*MovieData)(nil), "movie.MovieData")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75) }

var fileDescriptor_fde087a4194eda75 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xcf, 0x4a, 0xc3, 0x40,
	0x10, 0xc6, 0xdb, 0xc8, 0x16, 0x3b, 0x29, 0x62, 0xa7, 0x15, 0xd2, 0x1c, 0x4a, 0xd9, 0x7a, 0x08,
	0x1e, 0x0a, 0xa6, 0x77, 0x2f, 0x46, 0x7a, 0xd1, 0x4b, 0xde, 0x20, 0xb6, 0x23, 0x04, 0x22, 0xd1,
	0xee, 0x46, 0x7c, 0x0c, 0x1f, 0x59, 0x32, 0xbb, 0xa4, 0x9b, 0x3f, 0xc7, 0x99, 0xf9, 0xe6, 0x97,
	0xf9, 0xbe, 0x0d, 0xf8, 0x9f, 0xe5, 0x4f, 0x4e, 0xbb, 0xaf, 0x73, 0xa9, 0x4b, 0x14, 0x5c, 0xc8,
	0x7b, 0xc0, 0x84, 0x0a, 0xd2, 0xf4, 0x56, 0x97, 0x29, 0x7d, 0x57, 0xa4, 0x34, 0xde, 0x80, 0x97,
	0x9f, 0x82, 0xf1, 0x66, 0x1c, 0x89, 0xd4, 0xcb, 0x4f, 0x72, 0x0f, 0xf3, 0x96, 0x4a, 0x55, 0x85,
	0xc6, 0x35, 0x80, 0xaa, 0x8e, 0x47, 0x52, 0xea, 0xa3, 0x2a, 0x58, 0x7c, 0x9d, 0x3a, 0x1d, 0xf9,
	0x00, 0xf8, 0x7c, 0xa6, 0xac, 0x83, 0x5e, 0x82, 0xd0, 0xb9, 0x26, 0xb3, 0x30, 0x4d, 0x4d, 0x21,
	0xb7, 0x30, 0x6f, 0x69, 0xf9, 0x03, 0xdd, 0x2b, 0xee, 0x60, 0x71, 0x20, 0xcd, 0x8a, 0xd7, 0x5c,
	0x69, 0x4b, 0x94, 0x4f, 0x80, 0xed, 0x36, 0x2f, 0x47, 0x30, 0x61, 0x87, 0x2a, 0x18, 0x6f, 0xae,
	0x22, 0x3f, 0xbe, 0xdd, 0x19, 0xf7, 0xac, 0x4b, 0x32, 0x9d, 0xa5, 0x76, 0x2e, 0xd7, 0x30, 0x7b,
	0xf9, 0xbd, 0xf0, 0x7a, 0x9f, 0xdd, 0x82, 0x6f, 0xe7, 0x0c, 0x5e, 0x82, 0xa0, 0xba, 0xb4, 0x8e,
	0x4d, 0x21, 0x1f, 0x61, 0xda, 0x90, 0xbb, 0x84, 0x8b, 0x67, 0xcf, 0xf1, 0x1c, 0xff, 0x79, 0x20,
	0x78, 0x07, 0x13, 0xf0, 0x9d, 0x78, 0x71, 0x65, 0x4f, 0xed, 0x3f, 0x4c, 0x18, 0x0c, 0x8d, 0xea,
	0xb3, 0xe4, 0xa8, 0xa6, 0x38, 0x19, 0x36, 0x94, 0xfe, 0x1b, 0x34, 0x94, 0x5e, 0xe4, 0x72, 0x84,
	0x07, 0x98, 0xb9, 0x69, 0x62, 0x68, 0xb5, 0x03, 0xc9, 0x87, 0xab, 0xc1, 0x99, 0x05, 0xc5, 0x20,
	0x38, 0x36, 0x5c, 0x58, 0x95, 0x1b, 0x72, 0x88, 0xed, 0xa6, 0xd9, 0x79, 0x9f, 0xf0, 0xbf, 0xb9,
	0xff, 0x0f, 0x00, 0x00, 0xff, 0xff, 0x5b, 0x46, 0xe1, 0x2f, 0xaa, 0x02, 0x00, 0x00,
}
