// Code generated by protoc-gen-go. DO NOT EDIT.
// source: movie.proto

package movie

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteMovieRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieRequest) Reset()         { *m = DeleteMovieRequest{} }
func (m *DeleteMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieRequest) ProtoMessage()    {}
func (*DeleteMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{0}
}

func (m *DeleteMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieRequest.Unmarshal(m, b)
}
func (m *DeleteMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieRequest.Merge(m, src)
}
func (m *DeleteMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieRequest.Size(m)
}
func (m *DeleteMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieRequest proto.InternalMessageInfo

func (m *DeleteMovieRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteMovieResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteMovieResult) Reset()         { *m = DeleteMovieResult{} }
func (m *DeleteMovieResult) String() string { return proto.CompactTextString(m) }
func (*DeleteMovieResult) ProtoMessage()    {}
func (*DeleteMovieResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{1}
}

func (m *DeleteMovieResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteMovieResult.Unmarshal(m, b)
}
func (m *DeleteMovieResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteMovieResult.Marshal(b, m, deterministic)
}
func (m *DeleteMovieResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteMovieResult.Merge(m, src)
}
func (m *DeleteMovieResult) XXX_Size() int {
	return xxx_messageInfo_DeleteMovieResult.Size(m)
}
func (m *DeleteMovieResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteMovieResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteMovieResult proto.InternalMessageInfo

func (m *DeleteMovieResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateMovieRequest struct {
	Titel                string   `protobuf:"bytes,1,opt,name=titel,proto3" json:"titel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieRequest) Reset()         { *m = CreateMovieRequest{} }
func (m *CreateMovieRequest) String() string { return proto.CompactTextString(m) }
func (*CreateMovieRequest) ProtoMessage()    {}
func (*CreateMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{2}
}

func (m *CreateMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieRequest.Unmarshal(m, b)
}
func (m *CreateMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieRequest.Marshal(b, m, deterministic)
}
func (m *CreateMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieRequest.Merge(m, src)
}
func (m *CreateMovieRequest) XXX_Size() int {
	return xxx_messageInfo_CreateMovieRequest.Size(m)
}
func (m *CreateMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieRequest proto.InternalMessageInfo

func (m *CreateMovieRequest) GetTitel() string {
	if m != nil {
		return m.Titel
	}
	return ""
}

type CreateMovieResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateMovieResult) Reset()         { *m = CreateMovieResult{} }
func (m *CreateMovieResult) String() string { return proto.CompactTextString(m) }
func (*CreateMovieResult) ProtoMessage()    {}
func (*CreateMovieResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{3}
}

func (m *CreateMovieResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateMovieResult.Unmarshal(m, b)
}
func (m *CreateMovieResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateMovieResult.Marshal(b, m, deterministic)
}
func (m *CreateMovieResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateMovieResult.Merge(m, src)
}
func (m *CreateMovieResult) XXX_Size() int {
	return xxx_messageInfo_CreateMovieResult.Size(m)
}
func (m *CreateMovieResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateMovieResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateMovieResult proto.InternalMessageInfo

func (m *CreateMovieResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MovieData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Titel                string   `protobuf:"bytes,2,opt,name=titel,proto3" json:"titel,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MovieData) Reset()         { *m = MovieData{} }
func (m *MovieData) String() string { return proto.CompactTextString(m) }
func (*MovieData) ProtoMessage()    {}
func (*MovieData) Descriptor() ([]byte, []int) {
	return fileDescriptor_fde087a4194eda75, []int{4}
}

func (m *MovieData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MovieData.Unmarshal(m, b)
}
func (m *MovieData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MovieData.Marshal(b, m, deterministic)
}
func (m *MovieData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MovieData.Merge(m, src)
}
func (m *MovieData) XXX_Size() int {
	return xxx_messageInfo_MovieData.Size(m)
}
func (m *MovieData) XXX_DiscardUnknown() {
	xxx_messageInfo_MovieData.DiscardUnknown(m)
}

var xxx_messageInfo_MovieData proto.InternalMessageInfo

func (m *MovieData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MovieData) GetTitel() string {
	if m != nil {
		return m.Titel
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteMovieRequest)(nil), "movie.DeleteMovieRequest")
	proto.RegisterType((*DeleteMovieResult)(nil), "movie.DeleteMovieResult")
	proto.RegisterType((*CreateMovieRequest)(nil), "movie.CreateMovieRequest")
	proto.RegisterType((*CreateMovieResult)(nil), "movie.CreateMovieResult")
	proto.RegisterType((*MovieData)(nil), "movie.MovieData")
}

func init() { proto.RegisterFile("movie.proto", fileDescriptor_fde087a4194eda75) }

var fileDescriptor_fde087a4194eda75 = []byte{
	// 207 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xcd, 0x2f, 0xcb,
	0x4c, 0xd5, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x73, 0x94, 0x54, 0xb8, 0x84, 0x5c,
	0x52, 0x73, 0x52, 0x4b, 0x52, 0x7d, 0x41, 0xdc, 0xa0, 0xd4, 0xc2, 0xd2, 0xd4, 0xe2, 0x12, 0x21,
	0x3e, 0x2e, 0xa6, 0xcc, 0x14, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xd6, 0x20, 0xa6, 0xcc, 0x14, 0x25,
	0x63, 0x2e, 0x41, 0x14, 0x55, 0xc5, 0xa5, 0x39, 0x25, 0x42, 0x72, 0x5c, 0x5c, 0xc5, 0xa5, 0xc9,
	0xc9, 0xa9, 0xc5, 0xc5, 0x69, 0xa5, 0x39, 0x60, 0xc5, 0x1c, 0x41, 0x48, 0x22, 0x4a, 0x5a, 0x5c,
	0x42, 0xce, 0x45, 0xa9, 0x89, 0x68, 0x46, 0x8b, 0x70, 0xb1, 0x96, 0x64, 0x96, 0xa4, 0x42, 0x34,
	0x70, 0x06, 0x41, 0x38, 0x4a, 0xca, 0x5c, 0x82, 0x28, 0x6a, 0xc1, 0x16, 0xa0, 0xbb, 0xc2, 0x90,
	0x8b, 0x13, 0x2c, 0xed, 0x92, 0x58, 0x92, 0x88, 0x2e, 0x89, 0x30, 0x97, 0x09, 0xc9, 0x5c, 0xa3,
	0xc9, 0x8c, 0x5c, 0xac, 0x60, 0x3d, 0x42, 0x2e, 0x5c, 0xdc, 0x48, 0x5e, 0x10, 0x92, 0xd4, 0x83,
	0x04, 0x06, 0xa6, 0xe7, 0xa5, 0x24, 0xb0, 0x49, 0x81, 0x1c, 0xa4, 0xc4, 0x00, 0x32, 0x05, 0xc9,
	0x9d, 0x70, 0x53, 0x30, 0xfd, 0x09, 0x37, 0x05, 0xc3, 0x5b, 0x4a, 0x0c, 0x49, 0x6c, 0xe0, 0x28,
	0x30, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x52, 0x41, 0xd8, 0x88, 0x91, 0x01, 0x00, 0x00,
}
