// Code generated by protoc-gen-micro. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

import (
	context "context"
	client "github.com/micro/go-micro/client"
	server "github.com/micro/go-micro/server"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ client.Option
var _ server.Option

// Client API for User service

type UserService interface {
	DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*DeleteUserResult, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*CreateUserResult, error)
	BookingDeleted(ctx context.Context, in *BookingDeletedRequest, opts ...client.CallOption) (*BookingDeletedResult, error)
	CreatedMarkedBooking(ctx context.Context, in *CreatedBookingRequest, opts ...client.CallOption) (*CreatedBookingResult, error)
	CreatedBooking(ctx context.Context, in *CreatedBookingRequest, opts ...client.CallOption) (*CreatedBookingResult, error)
	GetUserList(ctx context.Context, in *GetUserListRequest, opts ...client.CallOption) (*GetUserListResult, error)
	Exist(ctx context.Context, in *ExistRequest, opts ...client.CallOption) (*ExistResult, error)
}

type userService struct {
	c    client.Client
	name string
}

func NewUserService(name string, c client.Client) UserService {
	if c == nil {
		c = client.NewClient()
	}
	if len(name) == 0 {
		name = "user"
	}
	return &userService{
		c:    c,
		name: name,
	}
}

func (c *userService) DeleteUser(ctx context.Context, in *DeleteUserRequest, opts ...client.CallOption) (*DeleteUserResult, error) {
	req := c.c.NewRequest(c.name, "User.DeleteUser", in)
	out := new(DeleteUserResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...client.CallOption) (*CreateUserResult, error) {
	req := c.c.NewRequest(c.name, "User.CreateUser", in)
	out := new(CreateUserResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) BookingDeleted(ctx context.Context, in *BookingDeletedRequest, opts ...client.CallOption) (*BookingDeletedResult, error) {
	req := c.c.NewRequest(c.name, "User.BookingDeleted", in)
	out := new(BookingDeletedResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreatedMarkedBooking(ctx context.Context, in *CreatedBookingRequest, opts ...client.CallOption) (*CreatedBookingResult, error) {
	req := c.c.NewRequest(c.name, "User.CreatedMarkedBooking", in)
	out := new(CreatedBookingResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) CreatedBooking(ctx context.Context, in *CreatedBookingRequest, opts ...client.CallOption) (*CreatedBookingResult, error) {
	req := c.c.NewRequest(c.name, "User.CreatedBooking", in)
	out := new(CreatedBookingResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) GetUserList(ctx context.Context, in *GetUserListRequest, opts ...client.CallOption) (*GetUserListResult, error) {
	req := c.c.NewRequest(c.name, "User.GetUserList", in)
	out := new(GetUserListResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userService) Exist(ctx context.Context, in *ExistRequest, opts ...client.CallOption) (*ExistResult, error) {
	req := c.c.NewRequest(c.name, "User.Exist", in)
	out := new(ExistResult)
	err := c.c.Call(ctx, req, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for User service

type UserHandler interface {
	DeleteUser(context.Context, *DeleteUserRequest, *DeleteUserResult) error
	CreateUser(context.Context, *CreateUserRequest, *CreateUserResult) error
	BookingDeleted(context.Context, *BookingDeletedRequest, *BookingDeletedResult) error
	CreatedMarkedBooking(context.Context, *CreatedBookingRequest, *CreatedBookingResult) error
	CreatedBooking(context.Context, *CreatedBookingRequest, *CreatedBookingResult) error
	GetUserList(context.Context, *GetUserListRequest, *GetUserListResult) error
	Exist(context.Context, *ExistRequest, *ExistResult) error
}

func RegisterUserHandler(s server.Server, hdlr UserHandler, opts ...server.HandlerOption) error {
	type user interface {
		DeleteUser(ctx context.Context, in *DeleteUserRequest, out *DeleteUserResult) error
		CreateUser(ctx context.Context, in *CreateUserRequest, out *CreateUserResult) error
		BookingDeleted(ctx context.Context, in *BookingDeletedRequest, out *BookingDeletedResult) error
		CreatedMarkedBooking(ctx context.Context, in *CreatedBookingRequest, out *CreatedBookingResult) error
		CreatedBooking(ctx context.Context, in *CreatedBookingRequest, out *CreatedBookingResult) error
		GetUserList(ctx context.Context, in *GetUserListRequest, out *GetUserListResult) error
		Exist(ctx context.Context, in *ExistRequest, out *ExistResult) error
	}
	type User struct {
		user
	}
	h := &userHandler{hdlr}
	return s.Handle(s.NewHandler(&User{h}, opts...))
}

type userHandler struct {
	UserHandler
}

func (h *userHandler) DeleteUser(ctx context.Context, in *DeleteUserRequest, out *DeleteUserResult) error {
	return h.UserHandler.DeleteUser(ctx, in, out)
}

func (h *userHandler) CreateUser(ctx context.Context, in *CreateUserRequest, out *CreateUserResult) error {
	return h.UserHandler.CreateUser(ctx, in, out)
}

func (h *userHandler) BookingDeleted(ctx context.Context, in *BookingDeletedRequest, out *BookingDeletedResult) error {
	return h.UserHandler.BookingDeleted(ctx, in, out)
}

func (h *userHandler) CreatedMarkedBooking(ctx context.Context, in *CreatedBookingRequest, out *CreatedBookingResult) error {
	return h.UserHandler.CreatedMarkedBooking(ctx, in, out)
}

func (h *userHandler) CreatedBooking(ctx context.Context, in *CreatedBookingRequest, out *CreatedBookingResult) error {
	return h.UserHandler.CreatedBooking(ctx, in, out)
}

func (h *userHandler) GetUserList(ctx context.Context, in *GetUserListRequest, out *GetUserListResult) error {
	return h.UserHandler.GetUserList(ctx, in, out)
}

func (h *userHandler) Exist(ctx context.Context, in *ExistRequest, out *ExistResult) error {
	return h.UserHandler.Exist(ctx, in, out)
}
