// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResult) Reset()         { *m = DeleteUserResult{} }
func (m *DeleteUserResult) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResult) ProtoMessage()    {}
func (*DeleteUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *DeleteUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResult.Unmarshal(m, b)
}
func (m *DeleteUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResult.Marshal(b, m, deterministic)
}
func (m *DeleteUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResult.Merge(m, src)
}
func (m *DeleteUserResult) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResult.Size(m)
}
func (m *DeleteUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResult proto.InternalMessageInfo

func (m *DeleteUserResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResult) Reset()         { *m = CreateUserResult{} }
func (m *CreateUserResult) String() string { return proto.CompactTextString(m) }
func (*CreateUserResult) ProtoMessage()    {}
func (*CreateUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResult.Unmarshal(m, b)
}
func (m *CreateUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResult.Marshal(b, m, deterministic)
}
func (m *CreateUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResult.Merge(m, src)
}
func (m *CreateUserResult) XXX_Size() int {
	return xxx_messageInfo_CreateUserResult.Size(m)
}
func (m *CreateUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResult proto.InternalMessageInfo

func (m *CreateUserResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BookingDeletedRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            int32    `protobuf:"varint,2,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingDeletedRequest) Reset()         { *m = BookingDeletedRequest{} }
func (m *BookingDeletedRequest) String() string { return proto.CompactTextString(m) }
func (*BookingDeletedRequest) ProtoMessage()    {}
func (*BookingDeletedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *BookingDeletedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingDeletedRequest.Unmarshal(m, b)
}
func (m *BookingDeletedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingDeletedRequest.Marshal(b, m, deterministic)
}
func (m *BookingDeletedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingDeletedRequest.Merge(m, src)
}
func (m *BookingDeletedRequest) XXX_Size() int {
	return xxx_messageInfo_BookingDeletedRequest.Size(m)
}
func (m *BookingDeletedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingDeletedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingDeletedRequest proto.InternalMessageInfo

func (m *BookingDeletedRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookingDeletedRequest) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type BookingDeletedResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingDeletedResult) Reset()         { *m = BookingDeletedResult{} }
func (m *BookingDeletedResult) String() string { return proto.CompactTextString(m) }
func (*BookingDeletedResult) ProtoMessage()    {}
func (*BookingDeletedResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *BookingDeletedResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingDeletedResult.Unmarshal(m, b)
}
func (m *BookingDeletedResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingDeletedResult.Marshal(b, m, deterministic)
}
func (m *BookingDeletedResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingDeletedResult.Merge(m, src)
}
func (m *BookingDeletedResult) XXX_Size() int {
	return xxx_messageInfo_BookingDeletedResult.Size(m)
}
func (m *BookingDeletedResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingDeletedResult.DiscardUnknown(m)
}

var xxx_messageInfo_BookingDeletedResult proto.InternalMessageInfo

type UserData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func init() {
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResult)(nil), "user.DeleteUserResult")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResult)(nil), "user.CreateUserResult")
	proto.RegisterType((*BookingDeletedRequest)(nil), "user.BookingDeletedRequest")
	proto.RegisterType((*BookingDeletedResult)(nil), "user.BookingDeletedResult")
	proto.RegisterType((*UserData)(nil), "user.UserData")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 272 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xc1, 0x4e, 0x83, 0x40,
	0x10, 0x86, 0x0b, 0xc1, 0xa6, 0xfd, 0x0f, 0x4d, 0x3b, 0x51, 0x6c, 0xd0, 0x18, 0xb3, 0x1e, 0xf4,
	0xc4, 0xa1, 0x3e, 0x80, 0x89, 0x72, 0x69, 0x8c, 0x17, 0x12, 0x1f, 0x80, 0x96, 0xd1, 0x10, 0xb1,
	0x28, 0xbb, 0xfb, 0xa8, 0xbe, 0x8f, 0xd9, 0xa5, 0x14, 0xba, 0xf4, 0xb6, 0xcc, 0xfc, 0xf3, 0xcd,
	0x3f, 0x7f, 0x00, 0xb4, 0xe4, 0x3a, 0xfe, 0xa9, 0x2b, 0x55, 0x51, 0x60, 0xde, 0xe2, 0x0e, 0x8b,
	0x84, 0x4b, 0x56, 0xfc, 0x2e, 0xb9, 0x4e, 0xf9, 0x57, 0xb3, 0x54, 0x34, 0x83, 0x5f, 0xe4, 0x4b,
	0xef, 0xd6, 0x7b, 0x38, 0x4b, 0xfd, 0x22, 0x17, 0x2b, 0xcc, 0xfb, 0x22, 0xa9, 0x4b, 0x45, 0x37,
	0x80, 0xd4, 0xdb, 0x2d, 0x4b, 0xf9, 0xa1, 0x4b, 0xab, 0x9d, 0xa4, 0xbd, 0x8a, 0xb8, 0xc7, 0xe2,
	0xa5, 0xe6, 0xec, 0x18, 0x4c, 0x08, 0x76, 0xd9, 0x37, 0x5b, 0xf9, 0x34, 0xb5, 0x6f, 0x21, 0x30,
	0xef, 0x0b, 0x2d, 0xdc, 0x35, 0xf0, 0x86, 0x8b, 0xe7, 0xaa, 0xfa, 0x2a, 0x76, 0x9f, 0x8d, 0x8f,
	0xbc, 0x05, 0x86, 0x18, 0x9b, 0x33, 0xd6, 0xc9, 0x5e, 0xbc, 0xff, 0xa2, 0x6b, 0x4c, 0x37, 0xcd,
	0xc0, 0x3a, 0x59, 0xfa, 0xb6, 0xd5, 0x15, 0x44, 0x88, 0x73, 0x17, 0x67, 0xd6, 0x8a, 0x18, 0x13,
	0x63, 0x22, 0xc9, 0x54, 0xe6, 0x5a, 0x38, 0x58, 0xf7, 0x3b, 0xeb, 0xab, 0x3f, 0x0f, 0x81, 0x19,
	0xa0, 0x27, 0xa0, 0x0b, 0x88, 0x2e, 0x63, 0x1b, 0xf3, 0x20, 0xd7, 0x28, 0x1c, 0x36, 0xec, 0xde,
	0x91, 0x01, 0x74, 0x21, 0xb4, 0x80, 0x41, 0x7e, 0x2d, 0xc0, 0xcd, 0x4b, 0x8c, 0xe8, 0x15, 0xb3,
	0xe3, 0x93, 0xe8, 0xaa, 0xd1, 0x9e, 0xcc, 0x2d, 0x8a, 0x4e, 0x37, 0x1b, 0xd8, 0x66, 0x6c, 0xff,
	0x90, 0xc7, 0xff, 0x00, 0x00, 0x00, 0xff, 0xff, 0x1a, 0x76, 0xc9, 0x72, 0x2f, 0x02, 0x00, 0x00,
}
