// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteUserRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserRequest) Reset()         { *m = DeleteUserRequest{} }
func (m *DeleteUserRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteUserRequest) ProtoMessage()    {}
func (*DeleteUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *DeleteUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserRequest.Unmarshal(m, b)
}
func (m *DeleteUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserRequest.Marshal(b, m, deterministic)
}
func (m *DeleteUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserRequest.Merge(m, src)
}
func (m *DeleteUserRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteUserRequest.Size(m)
}
func (m *DeleteUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserRequest proto.InternalMessageInfo

func (m *DeleteUserRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteUserResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteUserResult) Reset()         { *m = DeleteUserResult{} }
func (m *DeleteUserResult) String() string { return proto.CompactTextString(m) }
func (*DeleteUserResult) ProtoMessage()    {}
func (*DeleteUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *DeleteUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteUserResult.Unmarshal(m, b)
}
func (m *DeleteUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteUserResult.Marshal(b, m, deterministic)
}
func (m *DeleteUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteUserResult.Merge(m, src)
}
func (m *DeleteUserResult) XXX_Size() int {
	return xxx_messageInfo_DeleteUserResult.Size(m)
}
func (m *DeleteUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteUserResult proto.InternalMessageInfo

func (m *DeleteUserResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateUserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{2}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type CreateUserResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResult) Reset()         { *m = CreateUserResult{} }
func (m *CreateUserResult) String() string { return proto.CompactTextString(m) }
func (*CreateUserResult) ProtoMessage()    {}
func (*CreateUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{3}
}

func (m *CreateUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResult.Unmarshal(m, b)
}
func (m *CreateUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResult.Marshal(b, m, deterministic)
}
func (m *CreateUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResult.Merge(m, src)
}
func (m *CreateUserResult) XXX_Size() int {
	return xxx_messageInfo_CreateUserResult.Size(m)
}
func (m *CreateUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResult proto.InternalMessageInfo

func (m *CreateUserResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type BookingDeletedRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            int32    `protobuf:"varint,2,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingDeletedRequest) Reset()         { *m = BookingDeletedRequest{} }
func (m *BookingDeletedRequest) String() string { return proto.CompactTextString(m) }
func (*BookingDeletedRequest) ProtoMessage()    {}
func (*BookingDeletedRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{4}
}

func (m *BookingDeletedRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingDeletedRequest.Unmarshal(m, b)
}
func (m *BookingDeletedRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingDeletedRequest.Marshal(b, m, deterministic)
}
func (m *BookingDeletedRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingDeletedRequest.Merge(m, src)
}
func (m *BookingDeletedRequest) XXX_Size() int {
	return xxx_messageInfo_BookingDeletedRequest.Size(m)
}
func (m *BookingDeletedRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingDeletedRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BookingDeletedRequest proto.InternalMessageInfo

func (m *BookingDeletedRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookingDeletedRequest) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type BookingDeletedResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingDeletedResult) Reset()         { *m = BookingDeletedResult{} }
func (m *BookingDeletedResult) String() string { return proto.CompactTextString(m) }
func (*BookingDeletedResult) ProtoMessage()    {}
func (*BookingDeletedResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{5}
}

func (m *BookingDeletedResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingDeletedResult.Unmarshal(m, b)
}
func (m *BookingDeletedResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingDeletedResult.Marshal(b, m, deterministic)
}
func (m *BookingDeletedResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingDeletedResult.Merge(m, src)
}
func (m *BookingDeletedResult) XXX_Size() int {
	return xxx_messageInfo_BookingDeletedResult.Size(m)
}
func (m *BookingDeletedResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingDeletedResult.DiscardUnknown(m)
}

var xxx_messageInfo_BookingDeletedResult proto.InternalMessageInfo

type CreatedBookingRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	BookingID            int32    `protobuf:"varint,2,opt,name=bookingID,proto3" json:"bookingID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedBookingRequest) Reset()         { *m = CreatedBookingRequest{} }
func (m *CreatedBookingRequest) String() string { return proto.CompactTextString(m) }
func (*CreatedBookingRequest) ProtoMessage()    {}
func (*CreatedBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{6}
}

func (m *CreatedBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedBookingRequest.Unmarshal(m, b)
}
func (m *CreatedBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedBookingRequest.Marshal(b, m, deterministic)
}
func (m *CreatedBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedBookingRequest.Merge(m, src)
}
func (m *CreatedBookingRequest) XXX_Size() int {
	return xxx_messageInfo_CreatedBookingRequest.Size(m)
}
func (m *CreatedBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedBookingRequest proto.InternalMessageInfo

func (m *CreatedBookingRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreatedBookingRequest) GetBookingID() int32 {
	if m != nil {
		return m.BookingID
	}
	return 0
}

type CreatedBookingResult struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreatedBookingResult) Reset()         { *m = CreatedBookingResult{} }
func (m *CreatedBookingResult) String() string { return proto.CompactTextString(m) }
func (*CreatedBookingResult) ProtoMessage()    {}
func (*CreatedBookingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{7}
}

func (m *CreatedBookingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreatedBookingResult.Unmarshal(m, b)
}
func (m *CreatedBookingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreatedBookingResult.Marshal(b, m, deterministic)
}
func (m *CreatedBookingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreatedBookingResult.Merge(m, src)
}
func (m *CreatedBookingResult) XXX_Size() int {
	return xxx_messageInfo_CreatedBookingResult.Size(m)
}
func (m *CreatedBookingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreatedBookingResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreatedBookingResult proto.InternalMessageInfo

type GetUserListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserListRequest) Reset()         { *m = GetUserListRequest{} }
func (m *GetUserListRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserListRequest) ProtoMessage()    {}
func (*GetUserListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{8}
}

func (m *GetUserListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListRequest.Unmarshal(m, b)
}
func (m *GetUserListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListRequest.Marshal(b, m, deterministic)
}
func (m *GetUserListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListRequest.Merge(m, src)
}
func (m *GetUserListRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserListRequest.Size(m)
}
func (m *GetUserListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListRequest proto.InternalMessageInfo

type GetUserListResult struct {
	Users                []*UserData `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetUserListResult) Reset()         { *m = GetUserListResult{} }
func (m *GetUserListResult) String() string { return proto.CompactTextString(m) }
func (*GetUserListResult) ProtoMessage()    {}
func (*GetUserListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{9}
}

func (m *GetUserListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserListResult.Unmarshal(m, b)
}
func (m *GetUserListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserListResult.Marshal(b, m, deterministic)
}
func (m *GetUserListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserListResult.Merge(m, src)
}
func (m *GetUserListResult) XXX_Size() int {
	return xxx_messageInfo_GetUserListResult.Size(m)
}
func (m *GetUserListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserListResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserListResult proto.InternalMessageInfo

func (m *GetUserListResult) GetUsers() []*UserData {
	if m != nil {
		return m.Users
	}
	return nil
}

type ExistRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistRequest) Reset()         { *m = ExistRequest{} }
func (m *ExistRequest) String() string { return proto.CompactTextString(m) }
func (*ExistRequest) ProtoMessage()    {}
func (*ExistRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{10}
}

func (m *ExistRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistRequest.Unmarshal(m, b)
}
func (m *ExistRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistRequest.Marshal(b, m, deterministic)
}
func (m *ExistRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistRequest.Merge(m, src)
}
func (m *ExistRequest) XXX_Size() int {
	return xxx_messageInfo_ExistRequest.Size(m)
}
func (m *ExistRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ExistRequest proto.InternalMessageInfo

func (m *ExistRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ExistResult struct {
	Exist                bool     `protobuf:"varint,1,opt,name=exist,proto3" json:"exist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ExistResult) Reset()         { *m = ExistResult{} }
func (m *ExistResult) String() string { return proto.CompactTextString(m) }
func (*ExistResult) ProtoMessage()    {}
func (*ExistResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{11}
}

func (m *ExistResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ExistResult.Unmarshal(m, b)
}
func (m *ExistResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ExistResult.Marshal(b, m, deterministic)
}
func (m *ExistResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ExistResult.Merge(m, src)
}
func (m *ExistResult) XXX_Size() int {
	return xxx_messageInfo_ExistResult.Size(m)
}
func (m *ExistResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ExistResult.DiscardUnknown(m)
}

var xxx_messageInfo_ExistResult proto.InternalMessageInfo

func (m *ExistResult) GetExist() bool {
	if m != nil {
		return m.Exist
	}
	return false
}

type UserData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Bookings             []int32  `protobuf:"varint,3,rep,packed,name=bookings,proto3" json:"bookings,omitempty"`
	NotConfirmed         []int32  `protobuf:"varint,4,rep,packed,name=notConfirmed,proto3" json:"notConfirmed,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserData) Reset()         { *m = UserData{} }
func (m *UserData) String() string { return proto.CompactTextString(m) }
func (*UserData) ProtoMessage()    {}
func (*UserData) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{12}
}

func (m *UserData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserData.Unmarshal(m, b)
}
func (m *UserData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserData.Marshal(b, m, deterministic)
}
func (m *UserData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserData.Merge(m, src)
}
func (m *UserData) XXX_Size() int {
	return xxx_messageInfo_UserData.Size(m)
}
func (m *UserData) XXX_DiscardUnknown() {
	xxx_messageInfo_UserData.DiscardUnknown(m)
}

var xxx_messageInfo_UserData proto.InternalMessageInfo

func (m *UserData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *UserData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *UserData) GetBookings() []int32 {
	if m != nil {
		return m.Bookings
	}
	return nil
}

func (m *UserData) GetNotConfirmed() []int32 {
	if m != nil {
		return m.NotConfirmed
	}
	return nil
}

func init() {
	proto.RegisterType((*DeleteUserRequest)(nil), "user.DeleteUserRequest")
	proto.RegisterType((*DeleteUserResult)(nil), "user.DeleteUserResult")
	proto.RegisterType((*CreateUserRequest)(nil), "user.CreateUserRequest")
	proto.RegisterType((*CreateUserResult)(nil), "user.CreateUserResult")
	proto.RegisterType((*BookingDeletedRequest)(nil), "user.BookingDeletedRequest")
	proto.RegisterType((*BookingDeletedResult)(nil), "user.BookingDeletedResult")
	proto.RegisterType((*CreatedBookingRequest)(nil), "user.CreatedBookingRequest")
	proto.RegisterType((*CreatedBookingResult)(nil), "user.CreatedBookingResult")
	proto.RegisterType((*GetUserListRequest)(nil), "user.GetUserListRequest")
	proto.RegisterType((*GetUserListResult)(nil), "user.GetUserListResult")
	proto.RegisterType((*ExistRequest)(nil), "user.ExistRequest")
	proto.RegisterType((*ExistResult)(nil), "user.ExistResult")
	proto.RegisterType((*UserData)(nil), "user.UserData")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x94, 0x5d, 0x8b, 0xda, 0x40,
	0x14, 0x86, 0x35, 0x1f, 0xa2, 0x47, 0x11, 0x33, 0x58, 0x0d, 0x69, 0x11, 0x19, 0x0b, 0xf5, 0x4a,
	0x8a, 0xbd, 0xea, 0x55, 0x41, 0x53, 0x8a, 0xb4, 0x5e, 0x34, 0xb0, 0x3f, 0x20, 0x9a, 0x71, 0x09,
	0x6a, 0xb2, 0x9b, 0x99, 0xc0, 0xfe, 0xe7, 0xfd, 0x13, 0xcb, 0x7c, 0xe4, 0x3b, 0x77, 0xde, 0x65,
	0xce, 0xfb, 0xce, 0x73, 0x66, 0xe6, 0xbc, 0x04, 0x20, 0xa5, 0x24, 0xd9, 0xbc, 0x24, 0x31, 0x8b,
	0x91, 0xc1, 0xbf, 0xf1, 0x0a, 0x2c, 0x97, 0xdc, 0x08, 0x23, 0x4f, 0x94, 0x24, 0x1e, 0x79, 0x4d,
	0x09, 0x65, 0x68, 0x0c, 0x5a, 0x18, 0xd8, 0xdd, 0x65, 0x77, 0x6d, 0x7a, 0x5a, 0x18, 0xe0, 0x2d,
	0x4c, 0xca, 0x26, 0x9a, 0xde, 0x18, 0x5a, 0x00, 0xd0, 0xf4, 0x7c, 0x26, 0x94, 0x5e, 0xd2, 0x9b,
	0xf0, 0xf6, 0xbd, 0x52, 0x05, 0x7f, 0x03, 0x6b, 0x9f, 0x10, 0xbf, 0x0a, 0x46, 0x60, 0x44, 0xfe,
	0x9d, 0x08, 0xfb, 0xc0, 0x13, 0xdf, 0x18, 0xc3, 0xa4, 0x6c, 0x14, 0xf0, 0xfa, 0x01, 0x8e, 0xf0,
	0x69, 0x17, 0xc7, 0xd7, 0x30, 0x7a, 0x96, 0xe7, 0x08, 0x32, 0xe0, 0x0c, 0x7a, 0xfc, 0x1a, 0x07,
	0x57, 0x99, 0xd5, 0x0a, 0x7d, 0x81, 0xc1, 0x49, 0x6e, 0x38, 0xb8, 0xb6, 0x26, 0xa4, 0xa2, 0x80,
	0x67, 0x30, 0xad, 0xe3, 0x78, 0x5b, 0xde, 0x46, 0x1e, 0x25, 0x50, 0xf2, 0xc3, 0x6d, 0xea, 0x38,
	0xd1, 0x66, 0x0a, 0xe8, 0x0f, 0x61, 0xfc, 0xba, 0xff, 0x42, 0xca, 0x54, 0x0f, 0xfc, 0x13, 0xac,
	0x4a, 0x55, 0x3c, 0xc4, 0x57, 0x30, 0x79, 0x2b, 0x6a, 0x77, 0x97, 0xfa, 0x7a, 0xb8, 0x1d, 0x6f,
	0xc4, 0x00, 0xb9, 0xc9, 0xf5, 0x99, 0xef, 0x49, 0x11, 0x2f, 0x60, 0xf4, 0xfb, 0xad, 0x40, 0x35,
	0x9e, 0x6f, 0x05, 0x43, 0xa5, 0x0b, 0xe8, 0x14, 0x4c, 0xc2, 0x97, 0x6a, 0x6a, 0x72, 0x81, 0x23,
	0xe8, 0x67, 0xdc, 0x3a, 0x20, 0x9f, 0x9b, 0x56, 0xcc, 0x0d, 0x39, 0xd0, 0x57, 0x57, 0xa5, 0xb6,
	0xbe, 0xd4, 0xd7, 0xa6, 0x97, 0xaf, 0x11, 0x86, 0x51, 0x14, 0xb3, 0x7d, 0x1c, 0x5d, 0xc2, 0xe4,
	0x4e, 0x02, 0xdb, 0x10, 0x7a, 0xa5, 0xb6, 0x7d, 0xd7, 0xc1, 0xe0, 0x0d, 0xd1, 0x2f, 0x80, 0x22,
	0x5d, 0x68, 0x2e, 0xaf, 0xd8, 0x08, 0xa5, 0x33, 0x6b, 0x0a, 0xe2, 0x35, 0x3b, 0x1c, 0x50, 0x24,
	0x28, 0x03, 0x34, 0xc2, 0x97, 0x01, 0xea, 0x61, 0xc3, 0x1d, 0xf4, 0x17, 0xc6, 0xd5, 0x3c, 0xa0,
	0xcf, 0xd2, 0xdb, 0x1a, 0x3a, 0xc7, 0x69, 0x17, 0x15, 0xec, 0x7f, 0x3e, 0xf5, 0xa3, 0x9f, 0x5c,
	0xf3, 0xd9, 0x67, 0xc8, 0xd6, 0x80, 0x65, 0xc8, 0xd6, 0xb8, 0x88, 0xf3, 0x55, 0x95, 0x47, 0x60,
	0x3b, 0x18, 0x96, 0x72, 0x86, 0x6c, 0x69, 0x6e, 0x06, 0xd2, 0x99, 0xb7, 0x28, 0x8a, 0xf1, 0x1d,
	0x4c, 0x11, 0x28, 0x84, 0xa4, 0xa7, 0x9c, 0x3e, 0xc7, 0xaa, 0xd4, 0xe4, 0x8e, 0x53, 0x4f, 0xfc,
	0x74, 0x7e, 0x7c, 0x04, 0x00, 0x00, 0xff, 0xff, 0xa3, 0xc5, 0x8b, 0x36, 0x82, 0x04, 0x00, 0x00,
}
