// Code generated by protoc-gen-go. DO NOT EDIT.
// source: booking.proto

package booking

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteBookingRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingRequest) Reset()         { *m = DeleteBookingRequest{} }
func (m *DeleteBookingRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingRequest) ProtoMessage()    {}
func (*DeleteBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{0}
}

func (m *DeleteBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingRequest.Unmarshal(m, b)
}
func (m *DeleteBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingRequest.Marshal(b, m, deterministic)
}
func (m *DeleteBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingRequest.Merge(m, src)
}
func (m *DeleteBookingRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingRequest.Size(m)
}
func (m *DeleteBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingRequest proto.InternalMessageInfo

func (m *DeleteBookingRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteBookingResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteBookingResult) Reset()         { *m = DeleteBookingResult{} }
func (m *DeleteBookingResult) String() string { return proto.CompactTextString(m) }
func (*DeleteBookingResult) ProtoMessage()    {}
func (*DeleteBookingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{1}
}

func (m *DeleteBookingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteBookingResult.Unmarshal(m, b)
}
func (m *DeleteBookingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteBookingResult.Marshal(b, m, deterministic)
}
func (m *DeleteBookingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteBookingResult.Merge(m, src)
}
func (m *DeleteBookingResult) XXX_Size() int {
	return xxx_messageInfo_DeleteBookingResult.Size(m)
}
func (m *DeleteBookingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteBookingResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteBookingResult proto.InternalMessageInfo

func (m *DeleteBookingResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateBookingRequest struct {
	UserID               int32    `protobuf:"varint,1,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,2,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                int32    `protobuf:"varint,3,opt,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingRequest) Reset()         { *m = CreateBookingRequest{} }
func (m *CreateBookingRequest) String() string { return proto.CompactTextString(m) }
func (*CreateBookingRequest) ProtoMessage()    {}
func (*CreateBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{2}
}

func (m *CreateBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingRequest.Unmarshal(m, b)
}
func (m *CreateBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingRequest.Marshal(b, m, deterministic)
}
func (m *CreateBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingRequest.Merge(m, src)
}
func (m *CreateBookingRequest) XXX_Size() int {
	return xxx_messageInfo_CreateBookingRequest.Size(m)
}
func (m *CreateBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingRequest proto.InternalMessageInfo

func (m *CreateBookingRequest) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *CreateBookingRequest) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *CreateBookingRequest) GetSeats() int32 {
	if m != nil {
		return m.Seats
	}
	return 0
}

type CreateBookingResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateBookingResult) Reset()         { *m = CreateBookingResult{} }
func (m *CreateBookingResult) String() string { return proto.CompactTextString(m) }
func (*CreateBookingResult) ProtoMessage()    {}
func (*CreateBookingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{3}
}

func (m *CreateBookingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateBookingResult.Unmarshal(m, b)
}
func (m *CreateBookingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateBookingResult.Marshal(b, m, deterministic)
}
func (m *CreateBookingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateBookingResult.Merge(m, src)
}
func (m *CreateBookingResult) XXX_Size() int {
	return xxx_messageInfo_CreateBookingResult.Size(m)
}
func (m *CreateBookingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateBookingResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateBookingResult proto.InternalMessageInfo

func (m *CreateBookingResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ConfirmBookingRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingRequest) Reset()         { *m = ConfirmBookingRequest{} }
func (m *ConfirmBookingRequest) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingRequest) ProtoMessage()    {}
func (*ConfirmBookingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{4}
}

func (m *ConfirmBookingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingRequest.Unmarshal(m, b)
}
func (m *ConfirmBookingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingRequest.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingRequest.Merge(m, src)
}
func (m *ConfirmBookingRequest) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingRequest.Size(m)
}
func (m *ConfirmBookingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingRequest proto.InternalMessageInfo

func (m *ConfirmBookingRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ConfirmBookingResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfirmBookingResult) Reset()         { *m = ConfirmBookingResult{} }
func (m *ConfirmBookingResult) String() string { return proto.CompactTextString(m) }
func (*ConfirmBookingResult) ProtoMessage()    {}
func (*ConfirmBookingResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{5}
}

func (m *ConfirmBookingResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfirmBookingResult.Unmarshal(m, b)
}
func (m *ConfirmBookingResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfirmBookingResult.Marshal(b, m, deterministic)
}
func (m *ConfirmBookingResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfirmBookingResult.Merge(m, src)
}
func (m *ConfirmBookingResult) XXX_Size() int {
	return xxx_messageInfo_ConfirmBookingResult.Size(m)
}
func (m *ConfirmBookingResult) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfirmBookingResult.DiscardUnknown(m)
}

var xxx_messageInfo_ConfirmBookingResult proto.InternalMessageInfo

func (m *ConfirmBookingResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type AskBookingOfUserRequest struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskBookingOfUserRequest) Reset()         { *m = AskBookingOfUserRequest{} }
func (m *AskBookingOfUserRequest) String() string { return proto.CompactTextString(m) }
func (*AskBookingOfUserRequest) ProtoMessage()    {}
func (*AskBookingOfUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{6}
}

func (m *AskBookingOfUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskBookingOfUserRequest.Unmarshal(m, b)
}
func (m *AskBookingOfUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskBookingOfUserRequest.Marshal(b, m, deterministic)
}
func (m *AskBookingOfUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskBookingOfUserRequest.Merge(m, src)
}
func (m *AskBookingOfUserRequest) XXX_Size() int {
	return xxx_messageInfo_AskBookingOfUserRequest.Size(m)
}
func (m *AskBookingOfUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AskBookingOfUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AskBookingOfUserRequest proto.InternalMessageInfo

func (m *AskBookingOfUserRequest) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type AskBookingOfUserResult struct {
	NoBookings           bool     `protobuf:"varint,1,opt,name=noBookings,proto3" json:"noBookings,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AskBookingOfUserResult) Reset()         { *m = AskBookingOfUserResult{} }
func (m *AskBookingOfUserResult) String() string { return proto.CompactTextString(m) }
func (*AskBookingOfUserResult) ProtoMessage()    {}
func (*AskBookingOfUserResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{7}
}

func (m *AskBookingOfUserResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AskBookingOfUserResult.Unmarshal(m, b)
}
func (m *AskBookingOfUserResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AskBookingOfUserResult.Marshal(b, m, deterministic)
}
func (m *AskBookingOfUserResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AskBookingOfUserResult.Merge(m, src)
}
func (m *AskBookingOfUserResult) XXX_Size() int {
	return xxx_messageInfo_AskBookingOfUserResult.Size(m)
}
func (m *AskBookingOfUserResult) XXX_DiscardUnknown() {
	xxx_messageInfo_AskBookingOfUserResult.DiscardUnknown(m)
}

var xxx_messageInfo_AskBookingOfUserResult proto.InternalMessageInfo

func (m *AskBookingOfUserResult) GetNoBookings() bool {
	if m != nil {
		return m.NoBookings
	}
	return false
}

type FromShowDeleteRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FromShowDeleteRequest) Reset()         { *m = FromShowDeleteRequest{} }
func (m *FromShowDeleteRequest) String() string { return proto.CompactTextString(m) }
func (*FromShowDeleteRequest) ProtoMessage()    {}
func (*FromShowDeleteRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{8}
}

func (m *FromShowDeleteRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromShowDeleteRequest.Unmarshal(m, b)
}
func (m *FromShowDeleteRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromShowDeleteRequest.Marshal(b, m, deterministic)
}
func (m *FromShowDeleteRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromShowDeleteRequest.Merge(m, src)
}
func (m *FromShowDeleteRequest) XXX_Size() int {
	return xxx_messageInfo_FromShowDeleteRequest.Size(m)
}
func (m *FromShowDeleteRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FromShowDeleteRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FromShowDeleteRequest proto.InternalMessageInfo

func (m *FromShowDeleteRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FromShowDeleteResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FromShowDeleteResult) Reset()         { *m = FromShowDeleteResult{} }
func (m *FromShowDeleteResult) String() string { return proto.CompactTextString(m) }
func (*FromShowDeleteResult) ProtoMessage()    {}
func (*FromShowDeleteResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{9}
}

func (m *FromShowDeleteResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FromShowDeleteResult.Unmarshal(m, b)
}
func (m *FromShowDeleteResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FromShowDeleteResult.Marshal(b, m, deterministic)
}
func (m *FromShowDeleteResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FromShowDeleteResult.Merge(m, src)
}
func (m *FromShowDeleteResult) XXX_Size() int {
	return xxx_messageInfo_FromShowDeleteResult.Size(m)
}
func (m *FromShowDeleteResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FromShowDeleteResult.DiscardUnknown(m)
}

var xxx_messageInfo_FromShowDeleteResult proto.InternalMessageInfo

func (m *FromShowDeleteResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type BookingData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserID               int32    `protobuf:"varint,2,opt,name=userID,proto3" json:"userID,omitempty"`
	ShowID               int32    `protobuf:"varint,3,opt,name=showID,proto3" json:"showID,omitempty"`
	Seats                int32    `protobuf:"varint,4,opt,name=seats,proto3" json:"seats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BookingData) Reset()         { *m = BookingData{} }
func (m *BookingData) String() string { return proto.CompactTextString(m) }
func (*BookingData) ProtoMessage()    {}
func (*BookingData) Descriptor() ([]byte, []int) {
	return fileDescriptor_b881a7066599f9d6, []int{10}
}

func (m *BookingData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BookingData.Unmarshal(m, b)
}
func (m *BookingData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BookingData.Marshal(b, m, deterministic)
}
func (m *BookingData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BookingData.Merge(m, src)
}
func (m *BookingData) XXX_Size() int {
	return xxx_messageInfo_BookingData.Size(m)
}
func (m *BookingData) XXX_DiscardUnknown() {
	xxx_messageInfo_BookingData.DiscardUnknown(m)
}

var xxx_messageInfo_BookingData proto.InternalMessageInfo

func (m *BookingData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *BookingData) GetUserID() int32 {
	if m != nil {
		return m.UserID
	}
	return 0
}

func (m *BookingData) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *BookingData) GetSeats() int32 {
	if m != nil {
		return m.Seats
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteBookingRequest)(nil), "booking.DeleteBookingRequest")
	proto.RegisterType((*DeleteBookingResult)(nil), "booking.DeleteBookingResult")
	proto.RegisterType((*CreateBookingRequest)(nil), "booking.CreateBookingRequest")
	proto.RegisterType((*CreateBookingResult)(nil), "booking.CreateBookingResult")
	proto.RegisterType((*ConfirmBookingRequest)(nil), "booking.ConfirmBookingRequest")
	proto.RegisterType((*ConfirmBookingResult)(nil), "booking.ConfirmBookingResult")
	proto.RegisterType((*AskBookingOfUserRequest)(nil), "booking.AskBookingOfUserRequest")
	proto.RegisterType((*AskBookingOfUserResult)(nil), "booking.AskBookingOfUserResult")
	proto.RegisterType((*FromShowDeleteRequest)(nil), "booking.FromShowDeleteRequest")
	proto.RegisterType((*FromShowDeleteResult)(nil), "booking.FromShowDeleteResult")
	proto.RegisterType((*BookingData)(nil), "booking.BookingData")
}

func init() { proto.RegisterFile("booking.proto", fileDescriptor_b881a7066599f9d6) }

var fileDescriptor_b881a7066599f9d6 = []byte{
	// 370 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x54, 0x4f, 0x4f, 0xfa, 0x40,
	0x10, 0x85, 0xf2, 0x03, 0x7e, 0x19, 0x03, 0x31, 0x4b, 0x45, 0x42, 0x04, 0xc9, 0x26, 0xfe, 0x39,
	0x91, 0xa8, 0xd1, 0x78, 0x55, 0x1a, 0x13, 0x2e, 0x1a, 0x31, 0xc6, 0x8b, 0x97, 0x42, 0x17, 0x69,
	0xf8, 0xb3, 0xda, 0xd9, 0x86, 0xaf, 0xe4, 0xc7, 0x34, 0x6d, 0x17, 0xd9, 0x2e, 0x5b, 0xe4, 0x38,
	0x6f, 0x67, 0xde, 0xcc, 0xcb, 0x7b, 0x59, 0xa8, 0x0c, 0x39, 0x9f, 0xfa, 0x8b, 0x8f, 0xee, 0x67,
	0xc0, 0x05, 0x27, 0x65, 0x59, 0xd2, 0x53, 0xb0, 0x1d, 0x36, 0x63, 0x82, 0xdd, 0x27, 0xc0, 0x80,
	0x7d, 0x85, 0x0c, 0x05, 0xa9, 0x82, 0xe5, 0x7b, 0x8d, 0x7c, 0x27, 0x7f, 0x5e, 0x1c, 0x58, 0xbe,
	0x47, 0xaf, 0xa1, 0xa6, 0xf5, 0x61, 0x38, 0x13, 0xa4, 0x0d, 0x80, 0xe1, 0x68, 0xc4, 0x10, 0xc7,
	0xe1, 0x2c, 0x6e, 0xff, 0x3f, 0x50, 0x10, 0xfa, 0x0e, 0x76, 0x2f, 0x60, 0xee, 0x06, 0x7d, 0x1d,
	0x4a, 0x21, 0xb2, 0xa0, 0xef, 0xc8, 0x15, 0xb2, 0x8a, 0x70, 0x9c, 0xf0, 0x65, 0xdf, 0x69, 0x58,
	0x09, 0x9e, 0x54, 0xc4, 0x86, 0x22, 0x32, 0x57, 0x60, 0xa3, 0x10, 0xc3, 0x49, 0x41, 0x4f, 0xa0,
	0xa6, 0xb1, 0xc7, 0x47, 0xe9, 0xb7, 0x9f, 0xc1, 0x41, 0x8f, 0x2f, 0xc6, 0x7e, 0x30, 0xff, 0x43,
	0xe4, 0x0d, 0xd8, 0x7a, 0xe3, 0x4e, 0x2a, 0x2f, 0xe0, 0xf0, 0x0e, 0xa7, 0x72, 0xe6, 0x69, 0xfc,
	0x8a, 0x2c, 0xd0, 0x85, 0x7a, 0x29, 0xa1, 0x1e, 0xbd, 0x85, 0xfa, 0xe6, 0xc8, 0x6a, 0xd9, 0x82,
	0xcb, 0x07, 0x5c, 0x2d, 0x5b, 0x23, 0x91, 0x9a, 0x87, 0x80, 0xcf, 0x5f, 0x26, 0x7c, 0x99, 0x38,
	0xb2, 0x45, 0x8d, 0xde, 0xb8, 0x93, 0x9a, 0x11, 0xec, 0xc9, 0x65, 0x8e, 0x2b, 0x5c, 0x9d, 0x56,
	0xb1, 0xce, 0xca, 0xb0, 0xae, 0x60, 0xb6, 0xee, 0x9f, 0x62, 0xdd, 0xe5, 0x77, 0x01, 0xca, 0x72,
	0x0b, 0x79, 0x84, 0x4a, 0x2a, 0x5b, 0xa4, 0xd5, 0x5d, 0xa5, 0xd5, 0x94, 0xcd, 0xe6, 0x51, 0xd6,
	0x73, 0x24, 0x8f, 0xe6, 0x22, 0xbe, 0x54, 0x2c, 0x14, 0x3e, 0x53, 0x18, 0x15, 0x3e, 0x43, 0x9a,
	0x68, 0x8e, 0x3c, 0x43, 0x35, 0x1d, 0x0b, 0xd2, 0x5e, 0x4f, 0x98, 0x82, 0xd5, 0x6c, 0x65, 0xbe,
	0x4b, 0xca, 0x37, 0xd8, 0xd7, 0xed, 0x27, 0x9d, 0xdf, 0xa1, 0x8c, 0x30, 0x35, 0x8f, 0xb7, 0x74,
	0xac, 0x6f, 0x4d, 0x9b, 0xae, 0xdc, 0x6a, 0x8c, 0x8d, 0x72, 0xab, 0x29, 0x2d, 0x34, 0x37, 0x2c,
	0xc5, 0x5f, 0xc6, 0xd5, 0x4f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x83, 0x86, 0xaf, 0x20, 0x43, 0x04,
	0x00, 0x00,
}
