// Code generated by protoc-gen-go. DO NOT EDIT.
// source: show.proto

package show

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowRequest) Reset()         { *m = DeleteShowRequest{} }
func (m *DeleteShowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowRequest) ProtoMessage()    {}
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{0}
}

func (m *DeleteShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowRequest.Unmarshal(m, b)
}
func (m *DeleteShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowRequest.Merge(m, src)
}
func (m *DeleteShowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowRequest.Size(m)
}
func (m *DeleteShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowRequest proto.InternalMessageInfo

func (m *DeleteShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteShowResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowResult) Reset()         { *m = DeleteShowResult{} }
func (m *DeleteShowResult) String() string { return proto.CompactTextString(m) }
func (*DeleteShowResult) ProtoMessage()    {}
func (*DeleteShowResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{1}
}

func (m *DeleteShowResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowResult.Unmarshal(m, b)
}
func (m *DeleteShowResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowResult.Marshal(b, m, deterministic)
}
func (m *DeleteShowResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowResult.Merge(m, src)
}
func (m *DeleteShowResult) XXX_Size() int {
	return xxx_messageInfo_DeleteShowResult.Size(m)
}
func (m *DeleteShowResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowResult proto.InternalMessageInfo

func (m *DeleteShowResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateShowRequest struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	HallID               int32    `protobuf:"varint,2,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowRequest) Reset()         { *m = CreateShowRequest{} }
func (m *CreateShowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShowRequest) ProtoMessage()    {}
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{2}
}

func (m *CreateShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowRequest.Unmarshal(m, b)
}
func (m *CreateShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowRequest.Marshal(b, m, deterministic)
}
func (m *CreateShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowRequest.Merge(m, src)
}
func (m *CreateShowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShowRequest.Size(m)
}
func (m *CreateShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowRequest proto.InternalMessageInfo

func (m *CreateShowRequest) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *CreateShowRequest) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteShowOfHallRequest struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfHallRequest) Reset()         { *m = DeleteShowOfHallRequest{} }
func (m *DeleteShowOfHallRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfHallRequest) ProtoMessage()    {}
func (*DeleteShowOfHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{3}
}

func (m *DeleteShowOfHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfHallRequest.Unmarshal(m, b)
}
func (m *DeleteShowOfHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfHallRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfHallRequest.Merge(m, src)
}
func (m *DeleteShowOfHallRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfHallRequest.Size(m)
}
func (m *DeleteShowOfHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfHallRequest proto.InternalMessageInfo

func (m *DeleteShowOfHallRequest) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteShowOfHallResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfHallResult) Reset()         { *m = DeleteShowOfHallResult{} }
func (m *DeleteShowOfHallResult) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfHallResult) ProtoMessage()    {}
func (*DeleteShowOfHallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{4}
}

func (m *DeleteShowOfHallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfHallResult.Unmarshal(m, b)
}
func (m *DeleteShowOfHallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfHallResult.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfHallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfHallResult.Merge(m, src)
}
func (m *DeleteShowOfHallResult) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfHallResult.Size(m)
}
func (m *DeleteShowOfHallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfHallResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfHallResult proto.InternalMessageInfo

func (m *DeleteShowOfHallResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateShowResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowResult) Reset()         { *m = CreateShowResult{} }
func (m *CreateShowResult) String() string { return proto.CompactTextString(m) }
func (*CreateShowResult) ProtoMessage()    {}
func (*CreateShowResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{5}
}

func (m *CreateShowResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowResult.Unmarshal(m, b)
}
func (m *CreateShowResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowResult.Marshal(b, m, deterministic)
}
func (m *CreateShowResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowResult.Merge(m, src)
}
func (m *CreateShowResult) XXX_Size() int {
	return xxx_messageInfo_CreateShowResult.Size(m)
}
func (m *CreateShowResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowResult proto.InternalMessageInfo

func (m *CreateShowResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type ShowData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieID              int32    `protobuf:"varint,2,opt,name=movieID,proto3" json:"movieID,omitempty"`
	HallID               int32    `protobuf:"varint,3,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowData) Reset()         { *m = ShowData{} }
func (m *ShowData) String() string { return proto.CompactTextString(m) }
func (*ShowData) ProtoMessage()    {}
func (*ShowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{6}
}

func (m *ShowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowData.Unmarshal(m, b)
}
func (m *ShowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowData.Marshal(b, m, deterministic)
}
func (m *ShowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowData.Merge(m, src)
}
func (m *ShowData) XXX_Size() int {
	return xxx_messageInfo_ShowData.Size(m)
}
func (m *ShowData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowData.DiscardUnknown(m)
}

var xxx_messageInfo_ShowData proto.InternalMessageInfo

func (m *ShowData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowData) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *ShowData) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteShowRequest)(nil), "show.DeleteShowRequest")
	proto.RegisterType((*DeleteShowResult)(nil), "show.DeleteShowResult")
	proto.RegisterType((*CreateShowRequest)(nil), "show.CreateShowRequest")
	proto.RegisterType((*DeleteShowOfHallRequest)(nil), "show.DeleteShowOfHallRequest")
	proto.RegisterType((*DeleteShowOfHallResult)(nil), "show.DeleteShowOfHallResult")
	proto.RegisterType((*CreateShowResult)(nil), "show.CreateShowResult")
	proto.RegisterType((*ShowData)(nil), "show.ShowData")
}

func init() { proto.RegisterFile("show.proto", fileDescriptor_40dadfe47b432028) }

var fileDescriptor_40dadfe47b432028 = []byte{
	// 279 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xc1, 0x4b, 0xc3, 0x30,
	0x14, 0xc6, 0xd7, 0x3a, 0xe7, 0xf8, 0x0e, 0x63, 0xcb, 0xa1, 0x2b, 0x43, 0x45, 0xe2, 0xc5, 0xd3,
	0xc0, 0x79, 0xf1, 0xe6, 0xc1, 0x2a, 0x0e, 0x84, 0x41, 0xfd, 0x0b, 0xe2, 0xf6, 0x46, 0x0b, 0x19,
	0xd1, 0x26, 0x75, 0x7f, 0xab, 0xff, 0x8d, 0x24, 0x5b, 0x69, 0xda, 0x32, 0xf0, 0xd6, 0xf4, 0xcb,
	0xf7, 0x7b, 0xdf, 0x7b, 0x2f, 0x80, 0xce, 0xd4, 0x7e, 0xfe, 0x55, 0x28, 0xa3, 0x58, 0xdf, 0x7e,
	0xf3, 0x5b, 0x4c, 0x12, 0x92, 0x64, 0xe8, 0x23, 0x53, 0xfb, 0x94, 0xbe, 0x4b, 0xd2, 0x86, 0x8d,
	0x10, 0xe6, 0x9b, 0x38, 0xb8, 0x09, 0xee, 0xce, 0xd3, 0x30, 0xdf, 0xf0, 0x05, 0xc6, 0xfe, 0x25,
	0x5d, 0x4a, 0xc3, 0xae, 0x01, 0x5d, 0xae, 0xd7, 0xa4, 0xf5, 0xb6, 0x94, 0xee, 0xee, 0x30, 0xf5,
	0xfe, 0xf0, 0x17, 0x4c, 0x9e, 0x0b, 0x12, 0x4d, 0x70, 0x8c, 0x8b, 0x9d, 0xfa, 0xc9, 0x69, 0x99,
	0x1c, 0xe9, 0xd5, 0x91, 0x45, 0x18, 0x64, 0x42, 0xca, 0x65, 0x12, 0x87, 0x4e, 0x38, 0x9e, 0xf8,
	0x3d, 0xa6, 0x75, 0xe9, 0xd5, 0xf6, 0x4d, 0x48, 0x59, 0xc1, 0x6a, 0x4b, 0xd0, 0xb0, 0x3c, 0x22,
	0xea, 0x5a, 0xfe, 0x95, 0x99, 0x63, 0xec, 0x67, 0x76, 0x9e, 0xf6, 0x2c, 0xde, 0x31, 0xb4, 0x6a,
	0x22, 0x8c, 0x68, 0x6b, 0x7e, 0x7b, 0xe1, 0xa9, 0xf6, 0xce, 0xfc, 0xac, 0x8b, 0xdf, 0x00, 0x7d,
	0x8b, 0x63, 0x4f, 0x40, 0x1d, 0x9a, 0x4d, 0xe7, 0x6e, 0x51, 0x9d, 0xcd, 0xcc, 0xa2, 0xae, 0x60,
	0x53, 0xf2, 0x9e, 0x05, 0xd4, 0xd9, 0x2b, 0x40, 0x67, 0x03, 0x15, 0xa0, 0xdd, 0x26, 0xef, 0xb1,
	0x15, 0x46, 0xaf, 0x85, 0xda, 0xd9, 0x71, 0x1d, 0xf0, 0xec, 0xaa, 0x5d, 0xac, 0x31, 0xff, 0xd9,
	0xe5, 0x29, 0xf9, 0x00, 0xfc, 0x1c, 0xb8, 0x77, 0xf6, 0xf0, 0x17, 0x00, 0x00, 0xff, 0xff, 0xae,
	0x37, 0x3d, 0x38, 0x75, 0x02, 0x00, 0x00,
}
