// Code generated by protoc-gen-go. DO NOT EDIT.
// source: show.proto

package show

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeleteShowRequest struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowRequest) Reset()         { *m = DeleteShowRequest{} }
func (m *DeleteShowRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowRequest) ProtoMessage()    {}
func (*DeleteShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{0}
}

func (m *DeleteShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowRequest.Unmarshal(m, b)
}
func (m *DeleteShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowRequest.Merge(m, src)
}
func (m *DeleteShowRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowRequest.Size(m)
}
func (m *DeleteShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowRequest proto.InternalMessageInfo

func (m *DeleteShowRequest) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type DeleteShowResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowResult) Reset()         { *m = DeleteShowResult{} }
func (m *DeleteShowResult) String() string { return proto.CompactTextString(m) }
func (*DeleteShowResult) ProtoMessage()    {}
func (*DeleteShowResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{1}
}

func (m *DeleteShowResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowResult.Unmarshal(m, b)
}
func (m *DeleteShowResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowResult.Marshal(b, m, deterministic)
}
func (m *DeleteShowResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowResult.Merge(m, src)
}
func (m *DeleteShowResult) XXX_Size() int {
	return xxx_messageInfo_DeleteShowResult.Size(m)
}
func (m *DeleteShowResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowResult proto.InternalMessageInfo

func (m *DeleteShowResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateShowRequest struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	HallID               int32    `protobuf:"varint,2,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowRequest) Reset()         { *m = CreateShowRequest{} }
func (m *CreateShowRequest) String() string { return proto.CompactTextString(m) }
func (*CreateShowRequest) ProtoMessage()    {}
func (*CreateShowRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{2}
}

func (m *CreateShowRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowRequest.Unmarshal(m, b)
}
func (m *CreateShowRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowRequest.Marshal(b, m, deterministic)
}
func (m *CreateShowRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowRequest.Merge(m, src)
}
func (m *CreateShowRequest) XXX_Size() int {
	return xxx_messageInfo_CreateShowRequest.Size(m)
}
func (m *CreateShowRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowRequest proto.InternalMessageInfo

func (m *CreateShowRequest) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *CreateShowRequest) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteShowOfHallRequest struct {
	HallID               int32    `protobuf:"varint,1,opt,name=hallID,proto3" json:"hallID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfHallRequest) Reset()         { *m = DeleteShowOfHallRequest{} }
func (m *DeleteShowOfHallRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfHallRequest) ProtoMessage()    {}
func (*DeleteShowOfHallRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{3}
}

func (m *DeleteShowOfHallRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfHallRequest.Unmarshal(m, b)
}
func (m *DeleteShowOfHallRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfHallRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfHallRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfHallRequest.Merge(m, src)
}
func (m *DeleteShowOfHallRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfHallRequest.Size(m)
}
func (m *DeleteShowOfHallRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfHallRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfHallRequest proto.InternalMessageInfo

func (m *DeleteShowOfHallRequest) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

type DeleteShowOfHallResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfHallResult) Reset()         { *m = DeleteShowOfHallResult{} }
func (m *DeleteShowOfHallResult) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfHallResult) ProtoMessage()    {}
func (*DeleteShowOfHallResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{4}
}

func (m *DeleteShowOfHallResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfHallResult.Unmarshal(m, b)
}
func (m *DeleteShowOfHallResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfHallResult.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfHallResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfHallResult.Merge(m, src)
}
func (m *DeleteShowOfHallResult) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfHallResult.Size(m)
}
func (m *DeleteShowOfHallResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfHallResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfHallResult proto.InternalMessageInfo

func (m *DeleteShowOfHallResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type DeleteShowOfMovieRequest struct {
	MovieID              int32    `protobuf:"varint,1,opt,name=movieID,proto3" json:"movieID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfMovieRequest) Reset()         { *m = DeleteShowOfMovieRequest{} }
func (m *DeleteShowOfMovieRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfMovieRequest) ProtoMessage()    {}
func (*DeleteShowOfMovieRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{5}
}

func (m *DeleteShowOfMovieRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfMovieRequest.Unmarshal(m, b)
}
func (m *DeleteShowOfMovieRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfMovieRequest.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfMovieRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfMovieRequest.Merge(m, src)
}
func (m *DeleteShowOfMovieRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfMovieRequest.Size(m)
}
func (m *DeleteShowOfMovieRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfMovieRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfMovieRequest proto.InternalMessageInfo

func (m *DeleteShowOfMovieRequest) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

type DeleteShowOfMovieResult struct {
	Successful           bool     `protobuf:"varint,1,opt,name=successful,proto3" json:"successful,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteShowOfMovieResult) Reset()         { *m = DeleteShowOfMovieResult{} }
func (m *DeleteShowOfMovieResult) String() string { return proto.CompactTextString(m) }
func (*DeleteShowOfMovieResult) ProtoMessage()    {}
func (*DeleteShowOfMovieResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{6}
}

func (m *DeleteShowOfMovieResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteShowOfMovieResult.Unmarshal(m, b)
}
func (m *DeleteShowOfMovieResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteShowOfMovieResult.Marshal(b, m, deterministic)
}
func (m *DeleteShowOfMovieResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteShowOfMovieResult.Merge(m, src)
}
func (m *DeleteShowOfMovieResult) XXX_Size() int {
	return xxx_messageInfo_DeleteShowOfMovieResult.Size(m)
}
func (m *DeleteShowOfMovieResult) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteShowOfMovieResult.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteShowOfMovieResult proto.InternalMessageInfo

func (m *DeleteShowOfMovieResult) GetSuccessful() bool {
	if m != nil {
		return m.Successful
	}
	return false
}

type CreateShowResult struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateShowResult) Reset()         { *m = CreateShowResult{} }
func (m *CreateShowResult) String() string { return proto.CompactTextString(m) }
func (*CreateShowResult) ProtoMessage()    {}
func (*CreateShowResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{7}
}

func (m *CreateShowResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateShowResult.Unmarshal(m, b)
}
func (m *CreateShowResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateShowResult.Marshal(b, m, deterministic)
}
func (m *CreateShowResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateShowResult.Merge(m, src)
}
func (m *CreateShowResult) XXX_Size() int {
	return xxx_messageInfo_CreateShowResult.Size(m)
}
func (m *CreateShowResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateShowResult.DiscardUnknown(m)
}

var xxx_messageInfo_CreateShowResult proto.InternalMessageInfo

func (m *CreateShowResult) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

type FreeSeatsRequest struct {
	ShowID               int32    `protobuf:"varint,1,opt,name=ShowID,json=showID,proto3" json:"ShowID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSeatsRequest) Reset()         { *m = FreeSeatsRequest{} }
func (m *FreeSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsRequest) ProtoMessage()    {}
func (*FreeSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{8}
}

func (m *FreeSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsRequest.Unmarshal(m, b)
}
func (m *FreeSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsRequest.Marshal(b, m, deterministic)
}
func (m *FreeSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsRequest.Merge(m, src)
}
func (m *FreeSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsRequest.Size(m)
}
func (m *FreeSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsRequest proto.InternalMessageInfo

func (m *FreeSeatsRequest) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

type FreeSeatsResult struct {
	FreeSeats            int32    `protobuf:"varint,1,opt,name=freeSeats,proto3" json:"freeSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FreeSeatsResult) Reset()         { *m = FreeSeatsResult{} }
func (m *FreeSeatsResult) String() string { return proto.CompactTextString(m) }
func (*FreeSeatsResult) ProtoMessage()    {}
func (*FreeSeatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{9}
}

func (m *FreeSeatsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FreeSeatsResult.Unmarshal(m, b)
}
func (m *FreeSeatsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FreeSeatsResult.Marshal(b, m, deterministic)
}
func (m *FreeSeatsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FreeSeatsResult.Merge(m, src)
}
func (m *FreeSeatsResult) XXX_Size() int {
	return xxx_messageInfo_FreeSeatsResult.Size(m)
}
func (m *FreeSeatsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_FreeSeatsResult.DiscardUnknown(m)
}

var xxx_messageInfo_FreeSeatsResult proto.InternalMessageInfo

func (m *FreeSeatsResult) GetFreeSeats() int32 {
	if m != nil {
		return m.FreeSeats
	}
	return 0
}

type UpdateSeatsRequest struct {
	ShowID               int32    `protobuf:"varint,1,opt,name=ShowID,json=showID,proto3" json:"ShowID,omitempty"`
	AmountSeats          int32    `protobuf:"varint,2,opt,name=amountSeats,proto3" json:"amountSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSeatsRequest) Reset()         { *m = UpdateSeatsRequest{} }
func (m *UpdateSeatsRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateSeatsRequest) ProtoMessage()    {}
func (*UpdateSeatsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{10}
}

func (m *UpdateSeatsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSeatsRequest.Unmarshal(m, b)
}
func (m *UpdateSeatsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSeatsRequest.Marshal(b, m, deterministic)
}
func (m *UpdateSeatsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSeatsRequest.Merge(m, src)
}
func (m *UpdateSeatsRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateSeatsRequest.Size(m)
}
func (m *UpdateSeatsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSeatsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSeatsRequest proto.InternalMessageInfo

func (m *UpdateSeatsRequest) GetShowID() int32 {
	if m != nil {
		return m.ShowID
	}
	return 0
}

func (m *UpdateSeatsRequest) GetAmountSeats() int32 {
	if m != nil {
		return m.AmountSeats
	}
	return 0
}

type UpdateSeatsResult struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdateSeatsResult) Reset()         { *m = UpdateSeatsResult{} }
func (m *UpdateSeatsResult) String() string { return proto.CompactTextString(m) }
func (*UpdateSeatsResult) ProtoMessage()    {}
func (*UpdateSeatsResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{11}
}

func (m *UpdateSeatsResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateSeatsResult.Unmarshal(m, b)
}
func (m *UpdateSeatsResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateSeatsResult.Marshal(b, m, deterministic)
}
func (m *UpdateSeatsResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateSeatsResult.Merge(m, src)
}
func (m *UpdateSeatsResult) XXX_Size() int {
	return xxx_messageInfo_UpdateSeatsResult.Size(m)
}
func (m *UpdateSeatsResult) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateSeatsResult.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateSeatsResult proto.InternalMessageInfo

func (m *UpdateSeatsResult) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type GetShowListRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetShowListRequest) Reset()         { *m = GetShowListRequest{} }
func (m *GetShowListRequest) String() string { return proto.CompactTextString(m) }
func (*GetShowListRequest) ProtoMessage()    {}
func (*GetShowListRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{12}
}

func (m *GetShowListRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShowListRequest.Unmarshal(m, b)
}
func (m *GetShowListRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShowListRequest.Marshal(b, m, deterministic)
}
func (m *GetShowListRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShowListRequest.Merge(m, src)
}
func (m *GetShowListRequest) XXX_Size() int {
	return xxx_messageInfo_GetShowListRequest.Size(m)
}
func (m *GetShowListRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShowListRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetShowListRequest proto.InternalMessageInfo

type GetShowListResult struct {
	Shows                []*ShowData `protobuf:"bytes,1,rep,name=shows,proto3" json:"shows,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *GetShowListResult) Reset()         { *m = GetShowListResult{} }
func (m *GetShowListResult) String() string { return proto.CompactTextString(m) }
func (*GetShowListResult) ProtoMessage()    {}
func (*GetShowListResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{13}
}

func (m *GetShowListResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetShowListResult.Unmarshal(m, b)
}
func (m *GetShowListResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetShowListResult.Marshal(b, m, deterministic)
}
func (m *GetShowListResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetShowListResult.Merge(m, src)
}
func (m *GetShowListResult) XXX_Size() int {
	return xxx_messageInfo_GetShowListResult.Size(m)
}
func (m *GetShowListResult) XXX_DiscardUnknown() {
	xxx_messageInfo_GetShowListResult.DiscardUnknown(m)
}

var xxx_messageInfo_GetShowListResult proto.InternalMessageInfo

func (m *GetShowListResult) GetShows() []*ShowData {
	if m != nil {
		return m.Shows
	}
	return nil
}

type ShowData struct {
	Id                   int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MovieID              int32    `protobuf:"varint,2,opt,name=movieID,proto3" json:"movieID,omitempty"`
	HallID               int32    `protobuf:"varint,3,opt,name=hallID,proto3" json:"hallID,omitempty"`
	FreeSeats            int32    `protobuf:"varint,4,opt,name=freeSeats,proto3" json:"freeSeats,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShowData) Reset()         { *m = ShowData{} }
func (m *ShowData) String() string { return proto.CompactTextString(m) }
func (*ShowData) ProtoMessage()    {}
func (*ShowData) Descriptor() ([]byte, []int) {
	return fileDescriptor_40dadfe47b432028, []int{14}
}

func (m *ShowData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShowData.Unmarshal(m, b)
}
func (m *ShowData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShowData.Marshal(b, m, deterministic)
}
func (m *ShowData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShowData.Merge(m, src)
}
func (m *ShowData) XXX_Size() int {
	return xxx_messageInfo_ShowData.Size(m)
}
func (m *ShowData) XXX_DiscardUnknown() {
	xxx_messageInfo_ShowData.DiscardUnknown(m)
}

var xxx_messageInfo_ShowData proto.InternalMessageInfo

func (m *ShowData) GetId() int32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ShowData) GetMovieID() int32 {
	if m != nil {
		return m.MovieID
	}
	return 0
}

func (m *ShowData) GetHallID() int32 {
	if m != nil {
		return m.HallID
	}
	return 0
}

func (m *ShowData) GetFreeSeats() int32 {
	if m != nil {
		return m.FreeSeats
	}
	return 0
}

func init() {
	proto.RegisterType((*DeleteShowRequest)(nil), "show.DeleteShowRequest")
	proto.RegisterType((*DeleteShowResult)(nil), "show.DeleteShowResult")
	proto.RegisterType((*CreateShowRequest)(nil), "show.CreateShowRequest")
	proto.RegisterType((*DeleteShowOfHallRequest)(nil), "show.DeleteShowOfHallRequest")
	proto.RegisterType((*DeleteShowOfHallResult)(nil), "show.DeleteShowOfHallResult")
	proto.RegisterType((*DeleteShowOfMovieRequest)(nil), "show.DeleteShowOfMovieRequest")
	proto.RegisterType((*DeleteShowOfMovieResult)(nil), "show.DeleteShowOfMovieResult")
	proto.RegisterType((*CreateShowResult)(nil), "show.CreateShowResult")
	proto.RegisterType((*FreeSeatsRequest)(nil), "show.FreeSeatsRequest")
	proto.RegisterType((*FreeSeatsResult)(nil), "show.FreeSeatsResult")
	proto.RegisterType((*UpdateSeatsRequest)(nil), "show.UpdateSeatsRequest")
	proto.RegisterType((*UpdateSeatsResult)(nil), "show.UpdateSeatsResult")
	proto.RegisterType((*GetShowListRequest)(nil), "show.GetShowListRequest")
	proto.RegisterType((*GetShowListResult)(nil), "show.GetShowListResult")
	proto.RegisterType((*ShowData)(nil), "show.ShowData")
}

func init() { proto.RegisterFile("show.proto", fileDescriptor_40dadfe47b432028) }

var fileDescriptor_40dadfe47b432028 = []byte{
	// 480 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x94, 0x51, 0xaf, 0xd2, 0x30,
	0x14, 0xc7, 0x61, 0x70, 0xef, 0xc5, 0x43, 0x82, 0xac, 0x51, 0x58, 0x96, 0x0b, 0x21, 0xd5, 0x07,
	0x62, 0x22, 0x46, 0xf4, 0x41, 0xe2, 0x83, 0x51, 0x27, 0x4a, 0xa2, 0x92, 0x8c, 0xf8, 0x01, 0x26,
	0x94, 0x30, 0xdd, 0x2c, 0xae, 0x9d, 0x7c, 0x6f, 0x3f, 0x81, 0x69, 0xd7, 0x66, 0xdd, 0x2a, 0xb9,
	0xbc, 0xd1, 0x73, 0xce, 0xff, 0x77, 0x4e, 0xcf, 0xfe, 0x05, 0x80, 0x1d, 0xe8, 0x69, 0x76, 0xcc,
	0x28, 0xa7, 0xa8, 0x2d, 0x7e, 0xe3, 0x47, 0xe0, 0x06, 0x24, 0x21, 0x9c, 0x6c, 0x0e, 0xf4, 0x14,
	0x92, 0xdf, 0x39, 0x61, 0x1c, 0xf5, 0xc0, 0x89, 0x77, 0x5e, 0x73, 0xd2, 0x9c, 0x5e, 0x85, 0x4e,
	0xbc, 0xc3, 0x73, 0xe8, 0x9b, 0x45, 0x2c, 0x4f, 0x38, 0x1a, 0x03, 0xb0, 0x7c, 0xbb, 0x25, 0x8c,
	0xed, 0xf3, 0x44, 0xd6, 0x76, 0x42, 0x23, 0x82, 0x3f, 0x80, 0xfb, 0x3e, 0x23, 0x51, 0x15, 0xec,
	0xc1, 0x4d, 0x4a, 0xff, 0xc4, 0x64, 0x15, 0x28, 0xba, 0x3e, 0xa2, 0x01, 0x5c, 0x1f, 0xa2, 0x24,
	0x59, 0x05, 0x9e, 0x23, 0x13, 0xea, 0x84, 0x9f, 0xc3, 0xb0, 0x6c, 0xbd, 0xde, 0x7f, 0x8a, 0x92,
	0x44, 0xc3, 0x4a, 0x49, 0xb3, 0x22, 0x79, 0x05, 0x03, 0x5b, 0x72, 0xd1, 0xcc, 0x2f, 0xc1, 0x33,
	0x95, 0x5f, 0xc4, 0x6c, 0x77, 0x8e, 0x8e, 0x17, 0xd5, 0x11, 0x95, 0xea, 0xa2, 0x86, 0x18, 0xfa,
	0xe6, 0x92, 0xa4, 0xa6, 0xbe, 0xfc, 0x27, 0xd0, 0x5f, 0x66, 0x84, 0x6c, 0x48, 0xc4, 0x99, 0x71,
	0x75, 0xa1, 0x28, 0xaf, 0xce, 0xe4, 0x09, 0x3f, 0x83, 0xfb, 0x46, 0xad, 0xc4, 0xdd, 0xc2, 0xbd,
	0xbd, 0x0e, 0xa9, 0xea, 0x32, 0x80, 0xbf, 0x02, 0xfa, 0x76, 0xdc, 0x89, 0x01, 0x2e, 0xc0, 0xa3,
	0x09, 0x74, 0xa3, 0x94, 0xe6, 0xbf, 0x78, 0x41, 0x2b, 0xbe, 0x94, 0x19, 0xc2, 0x4f, 0xc1, 0xad,
	0xf0, 0xe4, 0x08, 0x1e, 0xdc, 0xa8, 0x3b, 0xab, 0x15, 0xe8, 0x23, 0x7e, 0x00, 0xe8, 0x23, 0xe1,
	0xa2, 0xd7, 0xe7, 0x98, 0x71, 0xd5, 0x1e, 0x2f, 0xc0, 0xad, 0x44, 0x25, 0xe4, 0x31, 0x5c, 0x89,
	0x29, 0x04, 0xa2, 0x35, 0xed, 0xce, 0x7b, 0x33, 0x69, 0x65, 0x51, 0x14, 0x44, 0x3c, 0x0a, 0x8b,
	0x24, 0xfe, 0x01, 0x1d, 0x1d, 0xaa, 0x2f, 0xd2, 0xfc, 0x82, 0xce, 0x39, 0xf3, 0xb5, 0x4c, 0x27,
	0x55, 0x77, 0xd7, 0xae, 0xed, 0x6e, 0xfe, 0xb7, 0x05, 0x6d, 0xd1, 0x0c, 0xbd, 0x01, 0x28, 0x0d,
	0x80, 0x86, 0xc5, 0x64, 0xd6, 0xab, 0xf2, 0x07, 0x76, 0x42, 0xdc, 0x0c, 0x37, 0x04, 0xa0, 0xb4,
	0x81, 0x06, 0x58, 0xaf, 0x47, 0x03, 0xea, 0x8e, 0xc1, 0x0d, 0xb4, 0x86, 0xde, 0x32, 0xa3, 0xa9,
	0xb0, 0x7a, 0x81, 0x47, 0xa3, 0x7a, 0xb3, 0xca, 0xdb, 0xf1, 0x6f, 0xcf, 0xa5, 0x15, 0x30, 0x14,
	0x46, 0xa2, 0xa9, 0xf4, 0xb2, 0x22, 0x8e, 0x6d, 0x89, 0xf9, 0x40, 0xfc, 0xd1, 0xd9, 0xbc, 0x62,
	0xbe, 0x86, 0xce, 0x5b, 0xf6, 0x53, 0xee, 0x0e, 0xa9, 0xab, 0xd4, 0x8d, 0xed, 0x3f, 0xb4, 0xe2,
	0x4a, 0xfc, 0x0e, 0xba, 0x86, 0xb1, 0x90, 0x57, 0xd4, 0xd9, 0xde, 0xf5, 0x87, 0xff, 0xc9, 0x94,
	0x0c, 0xc3, 0x57, 0x9a, 0x61, 0x1b, 0x50, 0x33, 0x2c, 0x13, 0xe2, 0xc6, 0xf7, 0x6b, 0xf9, 0xe7,
	0xf9, 0xe2, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3d, 0xa5, 0xd8, 0xe4, 0x4a, 0x05, 0x00, 0x00,
}
